MLIR: lib/Conversion/ArithToSPIRV/ArithToSPIRV.cpp File Reference
ArithToSPIRV.cpp File Reference
#include "mlir/Conversion/ArithToSPIRV/ArithToSPIRV.h"
#include "../SPIRVCommon/Pattern.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/Transforms/SPIRVConversion.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Support/Debug.h"
#include <cassert>
#include <memory>
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
This header declares functions that assit transformations in the MemRef dialect.
Macros
#define GEN_PASS_DEF_CONVERTARITHTOSPIRV
#define DEBUG_TYPE "arith-to-spirv-pattern"
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
Functions
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder)
Converts the given srcAttr into a boolean attribute if it holds an integral value.
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder)
Converts the given srcAttr to a new attribute of the given dstType.
static bool isBoolScalarOrVector (Type type)
Returns true if the given type is a boolean scalar or vector type.
static bool hasSameBitwidth (Type a, Type b)
Returns true if scalar/vector type a and b have the same number of bitwidth.
static LogicalResult getTypeConversionFailure (ConversionPatternRewriter &rewriter, Operation *op, Type srcType)
Returns a source type conversion failure for srcType and operation op.
static LogicalResult getTypeConversionFailure (ConversionPatternRewriter &rewriter, Operation *op)
Returns a source type conversion failure for the result type of op.
template<typename SignedAbsOp >
static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder &builder)
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arith-to-spirv-pattern"
Definition at line 31 of file ArithToSPIRV.cpp.
DISPATCH [1/2]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
  case cmpPredicate:                                                           \
    if (spirvOp::template hasTrait<OpTrait::spirv::UnsignedOp>() &&            \
        !getElementTypeOrSelf(srcType).isIndex() && srcType != dstType &&      \
        !hasSameBitwidth(srcType, dstType)) {                                  \
      return op.emitError(                                                     \
          "bitwidth emulation is not implemented yet on unsigned op");         \
    }                                                                          \
    rewriter.replaceOpWithNewOp<spirvOp>(op, adaptor.getLhs(),                 \
                                         adaptor.getRhs());                    \
    return success();
DISPATCH [2/2]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
  case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(op, adaptor.getLhs(),                 \
                                         adaptor.getRhs());                    \
    return success();
GEN_PASS_DEF_CONVERTARITHTOSPIRV
#define GEN_PASS_DEF_CONVERTARITHTOSPIRV
Definition at line 27 of file ArithToSPIRV.cpp.
Function Documentation
convertBoolAttr()
static BoolAttr convertBoolAttr (Attribute srcAttr, Builder builder) static
Converts the given srcAttr into a boolean attribute if it holds an integral value.
Returns null attribute if conversion fails.
Definition at line 263 of file ArithToSPIRV.cpp.
References mlir::Attribute::dyn_cast(), and mlir::Builder::getBoolAttr().
convertFloatAttr()
static FloatAttr convertFloatAttr (FloatAttr srcAttr, FloatType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if dstType is not 32-bit or conversion fails.
Definition at line 300 of file ArithToSPIRV.cpp.
References mlir::Builder::getF32FloatAttr(), and mlir::Type::isF32().
convertIntegerAttr()
static IntegerAttr convertIntegerAttr (IntegerAttr srcAttr, IntegerType dstType, Builder builder) static
Converts the given srcAttr to a new attribute of the given dstType.
Returns null attribute if conversion fails.
Definition at line 273 of file ArithToSPIRV.cpp.
References mlir::Builder::getIntegerAttr().
emulateSignedRemainder()
template<typename SignedAbsOp > static Value emulateSignedRemainder (Location loc, Value lhs, Value rhs, Value signOperand, OpBuilder & builder) static
Returns signed remainder for lhs and rhs and lets the result follow the sign of signOperand.
Note that this is needed for Vulkan. Per the Vulkan's SPIR-V environment spec, "for the OpSRem and OpSMod instructions, if either operand is negative the result is undefined." So we cannot directly use spirv.SRem/spirv.SMod if either operand can be negative. Emulate it via spirv.UMod.
Definition at line 526 of file ArithToSPIRV.cpp.
References mlir::presburger::abs(), mlir::OpBuilder::create(), and mlir::Value::getType().
getTypeConversionFailure() [1/2]
static LogicalResult getTypeConversionFailure (ConversionPatternRewriter & rewriter, Operation * op) static
Returns a source type conversion failure for the result type of op.
Definition at line 360 of file ArithToSPIRV.cpp.
getTypeConversionFailure() [2/2]
static LogicalResult getTypeConversionFailure (ConversionPatternRewriter & rewriter, Operation * op, Type srcType) static
Returns a source type conversion failure for srcType and operation op.
Definition at line 351 of file ArithToSPIRV.cpp.
hasSameBitwidth()
static bool hasSameBitwidth (Type a, Type b) static
Returns true if scalar/vector type a and b have the same number of bitwidth.
Definition at line 335 of file ArithToSPIRV.cpp.
isBoolScalarOrVector()
static bool isBoolScalarOrVector (Type type) static
Returns true if the given type is a boolean scalar or vector type.
Definition at line 322 of file ArithToSPIRV.cpp.
References mlir::Type::dyn_cast(), and mlir::Type::isInteger().