MLIR: mlir::transform::SingleOpMatcherOpTrait< OpTy > Class Template Reference
mlir::transform::SingleOpMatcherOpTrait< OpTy > Class Template Reference
#include "mlir/Dialect/Transform/IR/MatchInterfaces.h"
Public Member Functions
DiagnosedSilenceableFailure apply (TransformResults &results, TransformState &state)
void getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< OpTy, SingleOpMatcherOpTrait >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename OpTy>
class mlir::transform::SingleOpMatcherOpTrait< OpTy >
Definition at line 20 of file MatchInterfaces.h.
Member Function Documentation
apply()
template<typename OpTy > DiagnosedSilenceableFailure mlir::transform::SingleOpMatcherOpTrait< OpTy >::apply (TransformResults & results, TransformState & state) inline
Definition at line 53 of file MatchInterfaces.h.
References mlir::emitDefiniteFailure(), mlir::OpTrait::TraitBase< OpTy, SingleOpMatcherOpTrait >::getOperation(), and mlir::transform::TransformState::getPayloadOps().
getEffects()
template<typename OpTy > void mlir::transform::SingleOpMatcherOpTrait< OpTy >::getEffects (SmallVectorImpl< MemoryEffects::EffectInstance > & effects) inline
Definition at line 67 of file MatchInterfaces.h.
References mlir::OpTrait::TraitBase< OpTy, SingleOpMatcherOpTrait >::getOperation(), mlir::transform::onlyReadsHandle(), mlir::transform::onlyReadsPayload(), and mlir::transform::producesHandle().
verifyTrait()
template<typename OpTy > static LogicalResult mlir::transform::SingleOpMatcherOpTrait< OpTy >::verifyTrait (Operation * op) inline static
Definition at line 31 of file MatchInterfaces.h.
The documentation for this class was generated from the following file:
include/mlir/Dialect/Transform/IR/MatchInterfaces.h