MLIR: mlir::LLVM::detail::DebugImporter Class Reference
mlir::LLVM::detail::DebugImporter Class Reference
#include "Target/LLVMIR/DebugImporter.h"
Public Member Functions
DebugImporter (ModuleOp mlirModule)
Location translateLoc (llvm::DILocation *loc)
Translates the given LLVM debug location to an MLIR location.
void translate (llvm::Function *func, LLVMFuncOp funcOp)
Translates the debug information for the given function.
DINodeAttr translate (llvm::DINode *node)
Translates the given LLVM debug metadata to MLIR.
template<typename DINodeT >
auto translate (DINodeT *node)
Infers the metadata type and translates it to MLIR.
Detailed Description
Definition at line 30 of file DebugImporter.h.
Constructor & Destructor Documentation
DebugImporter()
mlir::LLVM::detail::DebugImporter::DebugImporter (ModuleOp mlirModule) inline
Definition at line 32 of file DebugImporter.h.
Member Function Documentation
translate() [1/3]
template<typename DINodeT > auto mlir::LLVM::detail::DebugImporter::translate (DINodeT * node) inline
Infers the metadata type and translates it to MLIR.
Definition at line 46 of file DebugImporter.h.
References translate().
translate() [2/3]
DINodeAttr DebugImporter::translate (llvm::DINode * node)
Translates the given LLVM debug metadata to MLIR.
Definition at line 176 of file DebugImporter.cpp.
translate() [3/3]
void DebugImporter::translate (llvm::Function * func, LLVMFuncOp funcOp)
Translates the debug information for the given function.
Definition at line 26 of file DebugImporter.cpp.
References mlir::get().
Referenced by translate(), and translateLoc().
translateLoc()
Location DebugImporter::translateLoc (llvm::DILocation * loc)
Translates the given LLVM debug location to an MLIR location.
Definition at line 230 of file DebugImporter.cpp.
References mlir::get(), and translate().
The documentation for this class was generated from the following files:
lib/Target/LLVMIR/DebugImporter.h
lib/Target/LLVMIR/DebugImporter.cpp