MLIR: mlir::sparse_tensor::StorageLayout Class Reference
mlir::sparse_tensor::StorageLayout Class Reference
Provides methods to access fields of a sparse tensor with the given encoding.
#include "Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.h"
Public Member Functions
StorageLayout (SparseTensorEncodingAttr enc)
FieldIndex getMemRefFieldIndex (SparseTensorFieldKind kind, std::optional< Level > lvl) const
Getters: get the field index for required field.
FieldIndex getMemRefFieldIndex (StorageSpecifierKind kind, std::optional< Level > lvl) const
std::pair< FieldIndex, unsigned > getFieldIndexAndStride (SparseTensorFieldKind kind, std::optional< Level > lvl) const
Static Public Member Functions
static unsigned getNumFieldsFromEncoding (SparseTensorEncodingAttr enc)
static void foreachFieldInSparseTensor (const SparseTensorEncodingAttr enc, llvm::function_ref< bool(FieldIndex, SparseTensorFieldKind, Level, DimLevelType)> callback)
Detailed Description
Provides methods to access fields of a sparse tensor with the given encoding.
Definition at line 158 of file SparseTensorStorageLayout.h.
Constructor & Destructor Documentation
StorageLayout()
mlir::sparse_tensor::StorageLayout::StorageLayout (SparseTensorEncodingAttr enc) inline explicit
Definition at line 160 of file SparseTensorStorageLayout.h.
Member Function Documentation
foreachFieldInSparseTensor()
static void mlir::sparse_tensor::StorageLayout::foreachFieldInSparseTensor (const SparseTensorEncodingAttr enc, llvm::function_ref< bool(FieldIndex, SparseTensorFieldKind, Level, DimLevelType)> callback) inline static
Definition at line 181 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::foreachFieldInSparseTensor().
getFieldIndexAndStride()
std::pair<FieldIndex, unsigned> mlir::sparse_tensor::StorageLayout::getFieldIndexAndStride (SparseTensorFieldKind kind, std::optional< Level > lvl) const inline
Definition at line 190 of file SparseTensorStorageLayout.h.
Referenced by mlir::sparse_tensor::SparseTensorDescriptorImpl< ValueArrayRef >::getCrdMemRefIndexAndStride().
getMemRefFieldIndex() [1/2]
FieldIndex mlir::sparse_tensor::StorageLayout::getMemRefFieldIndex (SparseTensorFieldKind kind, std::optional< Level > lvl) const inline
Getters: get the field index for required field.
Definition at line 166 of file SparseTensorStorageLayout.h.
getMemRefFieldIndex() [2/2]
FieldIndex mlir::sparse_tensor::StorageLayout::getMemRefFieldIndex (StorageSpecifierKind kind, std::optional< Level > lvl) const inline
Definition at line 171 of file SparseTensorStorageLayout.h.
getNumFieldsFromEncoding()
static unsigned mlir::sparse_tensor::StorageLayout::getNumFieldsFromEncoding (SparseTensorEncodingAttr enc) inline static
Definition at line 177 of file SparseTensorStorageLayout.h.
References mlir::sparse_tensor::getNumFieldsFromEncoding().
The documentation for this class was generated from the following file:
lib/Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.h