MLIR: mlir::sparse_tensor::SparseTensorStorage< P, C, V > Class Template Reference
mlir::sparse_tensor::SparseTensorStorage< P, C, V > Class Template Reference final
A memory-resident sparse tensor using a storage scheme based on per-level sparse/dense annotations.
#include "mlir/ExecutionEngine/SparseTensor/Storage.h"
Public Member Functions
SparseTensorStorage (uint64_t dimRank, const uint64_t *dimSizes, uint64_t lvlRank, const uint64_t *lvlSizes, const DimLevelType *lvlTypes, const uint64_t *lvl2dim, bool initializeValuesIfAllDense)
Constructs a sparse tensor with the given encoding, and allocates overhead storage according to some simple heuristics.
SparseTensorStorage (uint64_t dimRank, const uint64_t *dimSizes, uint64_t lvlRank, const DimLevelType *lvlTypes, const uint64_t *lvl2dim, SparseTensorCOO< V > &lvlCOO)
Constructs a sparse tensor with the given encoding, and initializes the contents from the COO.
SparseTensorStorage (uint64_t dimRank, const uint64_t *dimSizes, uint64_t lvlRank, const DimLevelType *lvlTypes, const uint64_t *lvl2dim, SparseTensorEnumeratorBase< V > &lvlEnumerator)
Constructs a sparse tensor with the given encoding, and initializes the contents from the enumerator.
~SparseTensorStorage () final=default
void getPositions (std::vector< P > **out, uint64_t lvl) final
Partially specialize these getter methods based on template types.
void getCoordinates (std::vector< C > **out, uint64_t lvl) final
void getValues (std::vector< V > **out) final
uint64_t getCrd (uint64_t lvl, uint64_t pos) const final
Gets the coordinate-value stored at the given level and position.
void lexInsert (const uint64_t *lvlCoords, V val) final
Partially specialize lexicographical insertions based on template types.
void expInsert (uint64_t *lvlCoords, V *values, bool *filled, uint64_t *added, uint64_t count) final
Partially specialize expanded insertions based on template types.
void endInsert () final
Finalizes lexicographic insertions.
void newEnumerator (SparseTensorEnumeratorBase< V > **out, uint64_t trgRank, const uint64_t *trgSizes, uint64_t srcRank, const uint64_t *src2trg) const final
Allocates a new enumerator for this class's <P,C,V> types and erase the <P,C> parts from the type.
SparseTensorCOO< V > * toCOO (uint64_t trgRank, const uint64_t *trgSizes, uint64_t srcRank, const uint64_t *src2trg) const
Allocates a new COO object and initializes it with the contents of this tensor under the given mapping from the getDimSizes() coordinate-space to the trgSizes coordinate-space.
Public Member Functions inherited from mlir::sparse_tensor::SparseTensorStorageBase
SparseTensorStorageBase (uint64_t dimRank, const uint64_t *dimSizes, uint64_t lvlRank, const uint64_t *lvlSizes, const DimLevelType *lvlTypes, const uint64_t *lvl2dim)
Constructs a new sparse-tensor storage object with the given encoding.
virtual ~SparseTensorStorageBase ()=default
uint64_t getDimRank () const
Gets the number of tensor-dimensions.
uint64_t getLvlRank () const
Gets the number of storage-levels.
const std::vector< uint64_t > & getDimSizes () const
Gets the tensor-dimension sizes array.
uint64_t getDimSize (uint64_t d) const
Safely looks up the size of the given tensor-dimension.
const std::vector< uint64_t > & getLvlSizes () const
Gets the storage-level sizes array.
uint64_t getLvlSize (uint64_t l) const
Safely looks up the size of the given storage-level.
const std::vector< uint64_t > & getLvl2Dim () const
Gets the level-to-dimension mapping.
const std::vector< DimLevelType > & getLvlTypes () const
Gets the level-types array.
DimLevelType getLvlType (uint64_t l) const
Safely looks up the type of the given level.
bool isDenseLvl (uint64_t l) const
Safely checks if the level uses dense storage.
bool isCompressedLvl (uint64_t l) const
Safely checks if the level uses compressed storage.
bool isSingletonLvl (uint64_t l) const
Safely checks if the level uses singleton storage.
bool isOrderedLvl (uint64_t l) const
Safely checks if the level is ordered.
bool isUniqueLvl (uint64_t l) const
Safely checks if the level is unique.
Static Public Member Functions
static SparseTensorStorage< P, C, V > * newEmpty (uint64_t dimRank, const uint64_t *dimSizes, uint64_t lvlRank, const uint64_t *lvlSizes, const DimLevelType *lvlTypes, const uint64_t *lvl2dim)
Allocates a new empty sparse tensor.
static SparseTensorStorage< P, C, V > * newFromCOO (uint64_t dimRank, const uint64_t *dimShape, uint64_t lvlRank, const DimLevelType *lvlTypes, const uint64_t *lvl2dim, SparseTensorCOO< V > &lvlCOO)
Allocates a new sparse tensor and initializes it from the given COO.
static SparseTensorStorage< P, C, V > * newFromSparseTensor (uint64_t dimRank, const uint64_t *dimShape, uint64_t lvlRank, const uint64_t *lvlSizes, const DimLevelType *lvlTypes, const uint64_t *lvl2dim, uint64_t srcRank, const uint64_t *src2lvl, const SparseTensorStorageBase &source)
Allocates a new sparse tensor and initializes it with the contents of another sparse tensor.
Friends
class SparseTensorEnumerator< P, C, V >
Additional Inherited Members
Protected Member Functions inherited from mlir::sparse_tensor::SparseTensorStorageBase
SparseTensorStorageBase (const SparseTensorStorageBase &)=default
SparseTensorStorageBase & operator= (const SparseTensorStorageBase &)=delete
Detailed Description
template<typename P, typename C, typename V>
class mlir::sparse_tensor::SparseTensorStorage< P, C, V >
A memory-resident sparse tensor using a storage scheme based on per-level sparse/dense annotations.
This data structure provides a bufferized form of a sparse tensor type. In contrast to generating setup methods for each differently annotated sparse tensor, this method provides a convenient "one-size-fits-all" solution that simply takes an input tensor and annotations to implement all required setup in a general manner.
Definition at line 283 of file Storage.h.
Constructor & Destructor Documentation
SparseTensorStorage() [1/3]
template<typename P , typename C , typename V > mlir::sparse_tensor::SparseTensorStorage< P, C, V >::SparseTensorStorage (uint64_t dimRank, const uint64_t * dimSizes, uint64_t lvlRank, const uint64_t * lvlSizes, const DimLevelType * lvlTypes, const uint64_t * lvl2dim, bool initializeValuesIfAllDense)
Constructs a sparse tensor with the given encoding, and allocates overhead storage according to some simple heuristics.
When the bool argument is true and lvlTypes are all dense, then this ctor will also initialize the values array with zeros. That argument should be true when an empty tensor is intended; whereas it should usually be false when the ctor will be followed up by some other form of initialization.
Preconditions/assertions are as per the SparseTensorStorageBase ctor.
Definition at line 999 of file Storage.h.
References ASSERT_DENSE_DLT, mlir::sparse_tensor::detail::checkedMul(), mlir::sparse_tensor::isCompressedDLT(), and mlir::sparse_tensor::isSingletonDLT().
SparseTensorStorage() [2/3]
template<typename P , typename C , typename V > mlir::sparse_tensor::SparseTensorStorage< P, C, V >::SparseTensorStorage (uint64_t dimRank, const uint64_t * dimSizes, uint64_t lvlRank, const DimLevelType * lvlTypes, const uint64_t * lvl2dim, SparseTensorCOO< V > & lvlCOO)
Constructs a sparse tensor with the given encoding, and initializes the contents from the COO.
This ctor performs the same heuristic overhead-storage allocation as the ctor taking a bool, and has the same preconditions/assertions (where we define lvlSizes = lvlCOO.getDimSizes().data()), with the following addition:
Asserts:
lvlRank == lvlCOO.getRank().
Definition at line 1036 of file Storage.h.
References mlir::sparse_tensor::SparseTensorCOO< V >::getDimSizes(), mlir::sparse_tensor::SparseTensorCOO< V >::getElements(), and mlir::sparse_tensor::SparseTensorCOO< V >::sort().
SparseTensorStorage() [3/3]
template<typename P , typename C , typename V > mlir::sparse_tensor::SparseTensorStorage< P, C, V >::SparseTensorStorage (uint64_t dimRank, const uint64_t * dimSizes, uint64_t lvlRank, const DimLevelType * lvlTypes, const uint64_t * lvl2dim, SparseTensorEnumeratorBase< V > & lvlEnumerator)
Constructs a sparse tensor with the given encoding, and initializes the contents from the enumerator.
This ctor allocates exactly the required amount of overhead storage, not using any heuristics. Preconditions/assertions are as per the SparseTensorStorageBase ctor (where we define lvlSizes = lvlEnumerator.getTrgSizes().data()), with the following addition:
Asserts:
lvlRank == lvlEnumerator.getTrgRank().
Definition at line 1055 of file Storage.h.
References ASSERT_DENSE_DLT, mlir::sparse_tensor::SparseTensorNNZ::forallCoords(), mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::forallElements(), mlir::sparse_tensor::SparseTensorStorageBase::getLvlRank(), mlir::sparse_tensor::SparseTensorStorageBase::getLvlSizes(), mlir::sparse_tensor::SparseTensorStorageBase::getLvlTypes(), mlir::sparse_tensor::SparseTensorEnumeratorBase< V >::getTrgRank(), mlir::sparse_tensor::SparseTensorNNZ::initialize(), mlir::sparse_tensor::isCompressedDLT(), mlir::sparse_tensor::isDenseDLT(), and mlir::sparse_tensor::isSingletonDLT().
~SparseTensorStorage()
template<typename P , typename C , typename V > mlir::sparse_tensor::SparseTensorStorage< P, C, V >::~SparseTensorStorage () final default
Member Function Documentation
endInsert()
template<typename P , typename C , typename V > void mlir::sparse_tensor::SparseTensorStorage< P, C, V >::endInsert () inline final virtual
Finalizes lexicographic insertions.
Implements mlir::sparse_tensor::SparseTensorStorageBase.
Definition at line 474 of file Storage.h.
expInsert()
template<typename P , typename C , typename V > void mlir::sparse_tensor::SparseTensorStorage< P, C, V >::expInsert (uint64_t * lvlCoords, V * values, bool * filled, uint64_t * added, uint64_t count) inline final
Partially specialize expanded insertions based on template types.
Definition at line 446 of file Storage.h.
References mlir::sparse_tensor::SparseTensorStorageBase::getLvlRank(), and mlir::sparse_tensor::SparseTensorStorage< P, C, V >::lexInsert().
getCoordinates()
template<typename P , typename C , typename V > void mlir::sparse_tensor::SparseTensorStorage< P, C, V >::getCoordinates (std::vector< C > ** out, uint64_t lvl) inline final
Definition at line 414 of file Storage.h.
References ASSERT_VALID_LVL.
getCrd()
template<typename P , typename C , typename V > uint64_t mlir::sparse_tensor::SparseTensorStorage< P, C, V >::getCrd (uint64_t lvl, uint64_t pos) const inline final virtual
Gets the coordinate-value stored at the given level and position.
Implements mlir::sparse_tensor::SparseTensorStorageBase.
Definition at line 424 of file Storage.h.
References ASSERT_COMPRESSED_OR_SINGLETON_LVL.
getPositions()
template<typename P , typename C , typename V > void mlir::sparse_tensor::SparseTensorStorage< P, C, V >::getPositions (std::vector< P > ** out, uint64_t lvl) inline final
Partially specialize these getter methods based on template types.
Definition at line 409 of file Storage.h.
References ASSERT_VALID_LVL.
getValues()
template<typename P , typename C , typename V > void mlir::sparse_tensor::SparseTensorStorage< P, C, V >::getValues (std::vector< V > ** out) inline final
Definition at line 419 of file Storage.h.
lexInsert()
template<typename P , typename C , typename V > void mlir::sparse_tensor::SparseTensorStorage< P, C, V >::lexInsert (const uint64_t * lvlCoords, V val) inline final
Partially specialize lexicographical insertions based on template types.
Definition at line 431 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, C, V >::expInsert().
newEmpty()
template<typename P , typename C , typename V > static SparseTensorStorage<P, C, V>* mlir::sparse_tensor::SparseTensorStorage< P, C, V >::newEmpty (uint64_t dimRank, const uint64_t * dimSizes, uint64_t lvlRank, const uint64_t * lvlSizes, const DimLevelType * lvlTypes, const uint64_t * lvl2dim) inline static
Allocates a new empty sparse tensor.
The preconditions/assertions are as per the SparseTensorStorageBase ctor; which is to say, the dimSizes and lvlSizes must both be "sizes" not "shapes", since there's nowhere to reconstruct dynamic sizes from.
Definition at line 343 of file Storage.h.
newEnumerator()
template<typename P , typename C , typename V > void mlir::sparse_tensor::SparseTensorStorage< P, C, V >::newEnumerator (SparseTensorEnumeratorBase< V > ** out, uint64_t trgRank, const uint64_t * trgSizes, uint64_t srcRank, const uint64_t * src2trg) const inline final
Allocates a new enumerator for this class's <P,C,V> types and erase the <P,C> parts from the type.
Callers must make sure to delete the enumerator when they're done with it.
Definition at line 484 of file Storage.h.
References mlir::sparse_tensor::SparseTensorStorage< P, C, V >::SparseTensorEnumerator< P, C, V >.
newFromCOO()
template<typename P , typename C , typename V > SparseTensorStorage< P, C, V > * mlir::sparse_tensor::SparseTensorStorage< P, C, V >::newFromCOO (uint64_t dimRank, const uint64_t * dimShape, uint64_t lvlRank, const DimLevelType * lvlTypes, const uint64_t * lvl2dim, SparseTensorCOO< V > & lvlCOO) static
Allocates a new sparse tensor and initializes it from the given COO.
The preconditions are as per the SparseTensorStorageBase ctor (where we define lvlSizes = lvlCOO.getDimSizes().data()), but using the following assertions in lieu of the base ctor's assertions:
Asserts:
dimRank and lvlRank are nonzero.
lvlRank == lvlCOO.getRank().
lvlCOO.getDimSizes() under the lvl2dim mapping is a refinement of dimShape.
Definition at line 950 of file Storage.h.
References mlir::sparse_tensor::SparseTensorCOO< V >::getDimSizes().
Referenced by mlir::sparse_tensor::SparseTensorReader::readSparseTensor().
newFromSparseTensor()
template<typename P , typename C , typename V > SparseTensorStorage< P, C, V > * mlir::sparse_tensor::SparseTensorStorage< P, C, V >::newFromSparseTensor (uint64_t dimRank, const uint64_t * dimShape, uint64_t lvlRank, const uint64_t * lvlSizes, const DimLevelType * lvlTypes, const uint64_t * lvl2dim, uint64_t srcRank, const uint64_t * src2lvl, const SparseTensorStorageBase & source) static
Allocates a new sparse tensor and initializes it with the contents of another sparse tensor.
Preconditions:
as per the SparseTensorStorageBase ctor.
src2lvl must be valid for srcRank, must map coordinates valid for source.getDimSizes() to coordinates valid for lvlSizes, and therefore must be the inverse of lvl2dim.
source must have the same value type V.
Asserts:
dimRank and lvlRank are nonzero.
srcRank == source.getDimRank().
lvlSizes contains only nonzero sizes.
source.getDimSizes() is a refinement of dimShape.
Definition at line 974 of file Storage.h.
References mlir::sparse_tensor::SparseTensorStorageBase::getDimRank(), and mlir::sparse_tensor::SparseTensorStorageBase::getDimSizes().
toCOO()
template<typename P , typename C , typename V > SparseTensorCOO<V>* mlir::sparse_tensor::SparseTensorStorage< P, C, V >::toCOO (uint64_t trgRank, const uint64_t * trgSizes, uint64_t srcRank, const uint64_t * src2trg) const inline
Allocates a new COO object and initializes it with the contents of this tensor under the given mapping from the getDimSizes() coordinate-space to the trgSizes coordinate-space.
Callers must make sure to delete the COO when they're done with it.
Preconditions/assertions are as per the SparseTensorEnumerator ctor.
Definition at line 498 of file Storage.h.
References mlir::sparse_tensor::SparseTensorEnumerator< P, C, V >::forallElements().
Friends And Related Function Documentation
SparseTensorEnumerator< P, C, V >
template<typename P , typename C , typename V > friend class SparseTensorEnumerator< P, C, V > friend
Definition at line 680 of file Storage.h.
Referenced by mlir::sparse_tensor::SparseTensorStorage< P, C, V >::newEnumerator().
The documentation for this class was generated from the following file:
include/mlir/ExecutionEngine/SparseTensor/Storage.h