MLIR: mlir::LLVM::ModuleImport Class Reference
mlir::LLVM::ModuleImport Class Reference
Module import implementation class that provides methods to import globals and functions from an LLVM module into an MLIR module.
#include "mlir/Target/LLVMIR/ModuleImport.h"
Public Member Functions
ModuleImport (ModuleOp mlirModule, std::unique_ptr< llvm::Module > llvmModule)
LogicalResult initializeImportInterface ()
Calls the LLVMImportInterface initialization that queries the registered dialect interfaces for the supported LLVM IR intrinsics and metadata kinds and builds the dispatch tables.
LogicalResult convertFunctions ()
Converts all functions of the LLVM module to MLIR functions.
LogicalResult convertGlobals ()
Converts all global variables of the LLVM module to MLIR global variables.
LogicalResult convertDataLayout ()
Converts the data layout of the LLVM module to an MLIR data layout specification.
void mapValue (llvm::Value *llvm, Value mlir)
Stores the mapping between an LLVM value and its MLIR counterpart.
Value & mapValue (llvm::Value *value)
Provides write-once access to store the MLIR value corresponding to the given LLVM value.
Value lookupValue (llvm::Value *value)
Returns the MLIR value mapped to the given LLVM value.
void mapNoResultOp (llvm::Instruction *llvm, Operation *mlir)
Stores a mapping between an LLVM instruction and the imported MLIR operation if the operation returns no result.
Operation *& mapNoResultOp (llvm::Instruction *inst)
Provides write-once access to store the MLIR operation corresponding to the given LLVM instruction if the operation returns no result.
Operation * lookupOperation (llvm::Instruction *inst)
Returns the MLIR operation mapped to the given LLVM instruction.
void mapBlock (llvm::BasicBlock *llvm, Block *mlir)
Stores the mapping between an LLVM block and its MLIR counterpart.
Block * lookupBlock (llvm::BasicBlock *block) const
Returns the MLIR block mapped to the given LLVM block.
FailureOr< Value > convertValue (llvm::Value *value)
Converts an LLVM value to an MLIR value, or returns failure if the conversion fails.
FailureOr< Value > convertMetadataValue (llvm::Value *value)
Converts an LLVM metadata value to an MLIR value, or returns failure if the conversion fails.
FailureOr< SmallVector< Value > > convertValues (ArrayRef< llvm::Value * > values)
Converts a range of LLVM values to a range of MLIR values using the convertValue method, or returns failure if the conversion fails.
IntegerAttr matchIntegerAttr (llvm::Value *value)
Converts value to an integer attribute. Asserts if the matching fails.
DILocalVariableAttr matchLocalVariableAttr (llvm::Value *value)
Converts value to a local variable attribute.
FailureOr< SmallVector< SymbolRefAttr > > matchAliasScopeAttrs (llvm::Value *value)
Converts value to an array of symbol references pointing to alias scope operations, or returns failure if the conversion fails.
Location translateLoc (llvm::DILocation *loc)
Translates the debug location.
Type convertType (llvm::Type *type)
Converts the type from LLVM to MLIR LLVM dialect.
LogicalResult processFunction (llvm::Function *func)
Imports func into the current module.
void processFunctionAttributes (llvm::Function *func, LLVMFuncOp funcOp)
Converts function attributes of LLVM Function func into LLVM dialect attributes of LLVMFuncOp funcOp.
void setFastmathFlagsAttr (llvm::Instruction *inst, Operation *op) const
Sets the fastmath flags attribute for the imported operation op given the original instruction inst.
LogicalResult convertMetadata ()
Converts all LLVM metadata nodes that translate to operations nested in a global metadata operation, such as alias analysis or access group metadata, and builds a map from the metadata nodes to the symbols pointing to the converted operations.
SymbolRefAttr lookupTBAAAttr (const llvm::MDNode *node) const
Returns the MLIR symbol reference mapped to the given LLVM TBAA metadata node.
FailureOr< SmallVector< SymbolRefAttr > > lookupAccessGroupAttrs (const llvm::MDNode *node) const
Returns the symbol references pointing to the access group operations that map to the access group nodes starting from the access group metadata node.
LoopAnnotationAttr translateLoopAnnotationAttr (const llvm::MDNode *node, Location loc) const
Returns the loop annotation attribute that corresponds to the given LLVM loop metadata node.
FailureOr< SmallVector< SymbolRefAttr > > lookupAliasScopeAttrs (const llvm::MDNode *node) const
Returns the symbol references pointing to the alias scope operations that map to the alias scope nodes starting from the metadata node.
Detailed Description
Module import implementation class that provides methods to import globals and functions from an LLVM module into an MLIR module.
It holds mappings between the original and translated globals, basic blocks, and values used during the translation. Additionally, it keeps track of the current constant insertion point since LLVM immediate values translate to MLIR operations that are introduced at the beginning of the region.
Definition at line 46 of file ModuleImport.h.
Constructor & Destructor Documentation
ModuleImport()
ModuleImport::ModuleImport (ModuleOp mlirModule, std::unique_ptr< llvm::Module > llvmModule)
Definition at line 148 of file ModuleImport.cpp.
References mlir::OpBuilder::setInsertionPointToStart().
Member Function Documentation
convertDataLayout()
LogicalResult ModuleImport::convertDataLayout ()
Converts the data layout of the LLVM module to an MLIR data layout specification.
Definition at line 561 of file ModuleImport.cpp.
References mlir::emitError(), mlir::emitWarning(), mlir::LLVM::detail::DataLayoutImporter::getDataLayout(), mlir::LLVM::detail::DataLayoutImporter::getLastToken(), mlir::LLVM::detail::DataLayoutImporter::getUnhandledTokens(), and mlir::success().
Referenced by mlir::translateLLVMIRToModule().
convertFunctions()
LogicalResult ModuleImport::convertFunctions ()
Converts all functions of the LLVM module to MLIR functions.
Definition at line 576 of file ModuleImport.cpp.
References mlir::failed(), mlir::failure(), processFunction(), and mlir::success().
Referenced by mlir::translateLLVMIRToModule().
convertGlobals()
LogicalResult ModuleImport::convertGlobals ()
Converts all global variables of the LLVM module to MLIR global variables.
Definition at line 543 of file ModuleImport.cpp.
References diag(), mlir::emitError(), mlir::failed(), getGlobalCtorsVarName(), getGlobalDtorsVarName(), and mlir::success().
Referenced by mlir::translateLLVMIRToModule().
convertMetadata()
LogicalResult ModuleImport::convertMetadata ()
Converts all LLVM metadata nodes that translate to operations nested in a global metadata operation, such as alias analysis or access group metadata, and builds a map from the metadata nodes to the symbols pointing to the converted operations.
Returns success if all conversions succeed and failure otherwise.
Definition at line 514 of file ModuleImport.cpp.
References mlir::failed(), mlir::failure(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().
Referenced by mlir::translateLLVMIRToModule().
convertMetadataValue()
FailureOr< Value > ModuleImport::convertMetadataValue (llvm::Value * value)
Converts an LLVM metadata value to an MLIR value, or returns failure if the conversion fails.
Uses the convertConstant method to translate constant LLVM values.
Definition at line 1076 of file ModuleImport.cpp.
References mlir::failure(), and lookupValue().
convertType()
Type mlir::LLVM::ModuleImport::convertType (llvm::Type * type) inline
Converts the type from LLVM to MLIR LLVM dialect.
Definition at line 152 of file ModuleImport.h.
References mlir::LLVM::TypeFromLLVMIRTranslator::translateType().
Referenced by processFunction().
convertValue()
FailureOr< Value > ModuleImport::convertValue (llvm::Value * value)
Converts an LLVM value to an MLIR value, or returns failure if the conversion fails.
Uses the convertConstant method to translate constant LLVM values.
Definition at line 1058 of file ModuleImport.cpp.
References diag(), mlir::emitError(), lookupValue(), and translateLoc().
Referenced by convertValues(), and matchIntegerAttr().
convertValues()
FailureOr< SmallVector< Value > > ModuleImport::convertValues (ArrayRef< llvm::Value * > values)
Converts a range of LLVM values to a range of MLIR values using the convertValue method, or returns failure if the conversion fails.
Definition at line 1098 of file ModuleImport.cpp.
References convertValue(), mlir::failed(), and mlir::failure().
initializeImportInterface()
LogicalResult mlir::LLVM::ModuleImport::initializeImportInterface () inline
Calls the LLVMImportInterface initialization that queries the registered dialect interfaces for the supported LLVM IR intrinsics and metadata kinds and builds the dispatch tables.
Returns failure if multiple dialect interfaces translate the same LLVM IR intrinsic.
Definition at line 54 of file ModuleImport.h.
References mlir::LLVMImportInterface::initializeImport().
Referenced by mlir::translateLLVMIRToModule().
lookupAccessGroupAttrs()
FailureOr< SmallVector< SymbolRefAttr > > ModuleImport::lookupAccessGroupAttrs (const llvm::MDNode * node) const
Returns the symbol references pointing to the access group operations that map to the access group nodes starting from the access group metadata node.
Returns failure, if any of the symbol references cannot be found.
Definition at line 1659 of file ModuleImport.cpp.
lookupAliasScopeAttrs()
FailureOr< SmallVector< SymbolRefAttr > > ModuleImport::lookupAliasScopeAttrs (const llvm::MDNode * node) const
Returns the symbol references pointing to the alias scope operations that map to the alias scope nodes starting from the metadata node.
Returns failure, if any of the symbol references cannot be found.
Definition at line 501 of file ModuleImport.cpp.
References mlir::failure().
Referenced by matchAliasScopeAttrs().
lookupBlock()
Block* mlir::LLVM::ModuleImport::lookupBlock (llvm::BasicBlock * block) const inline
Returns the MLIR block mapped to the given LLVM block.
Definition at line 118 of file ModuleImport.h.
lookupOperation()
Operation* mlir::LLVM::ModuleImport::lookupOperation (llvm::Instruction * inst) inline
Returns the MLIR operation mapped to the given LLVM instruction.
Queries valueMapping and noResultOpMapping to support operations with and without result.
Definition at line 104 of file ModuleImport.h.
References lookupValue().
lookupTBAAAttr()
SymbolRefAttr mlir::LLVM::ModuleImport::lookupTBAAAttr (const llvm::MDNode * node) const inline
Returns the MLIR symbol reference mapped to the given LLVM TBAA metadata node.
Definition at line 179 of file ModuleImport.h.
lookupValue()
Value mlir::LLVM::ModuleImport::lookupValue (llvm::Value * value) inline
Returns the MLIR value mapped to the given LLVM value.
Definition at line 79 of file ModuleImport.h.
Referenced by convertMetadataValue(), convertValue(), and lookupOperation().
mapBlock()
void mlir::LLVM::ModuleImport::mapBlock (llvm::BasicBlock * llvm, Block * mlir) inline
Stores the mapping between an LLVM block and its MLIR counterpart.
Definition at line 111 of file ModuleImport.h.
mapNoResultOp() [1/2]
Operation*& mlir::LLVM::ModuleImport::mapNoResultOp (llvm::Instruction * inst) inline
Provides write-once access to store the MLIR operation corresponding to the given LLVM instruction if the operation returns no result.
Asserts if the operation returns a result and should be added to valueMapping instead.
Definition at line 92 of file ModuleImport.h.
mapNoResultOp() [2/2]
void mlir::LLVM::ModuleImport::mapNoResultOp (llvm::Instruction * llvm, Operation * mlir) inline
Stores a mapping between an LLVM instruction and the imported MLIR operation if the operation returns no result.
Asserts if the operation returns a result and should be added to valueMapping instead.
Definition at line 84 of file ModuleImport.h.
mapValue() [1/2]
void mlir::LLVM::ModuleImport::mapValue (llvm::Value * llvm, Value mlir) inline
Stores the mapping between an LLVM value and its MLIR counterpart.
Definition at line 67 of file ModuleImport.h.
References mapValue().
Referenced by mapValue().
mapValue() [2/2]
Value& mlir::LLVM::ModuleImport::mapValue (llvm::Value * value) inline
Provides write-once access to store the MLIR value corresponding to the given LLVM value.
Definition at line 71 of file ModuleImport.h.
matchAliasScopeAttrs()
FailureOr< SmallVector< SymbolRefAttr > > ModuleImport::matchAliasScopeAttrs (llvm::Value * value)
Converts value to an array of symbol references pointing to alias scope operations, or returns failure if the conversion fails.
Definition at line 1127 of file ModuleImport.cpp.
References lookupAliasScopeAttrs().
matchIntegerAttr()
IntegerAttr ModuleImport::matchIntegerAttr (llvm::Value * value)
Converts value to an integer attribute. Asserts if the matching fails.
Definition at line 1110 of file ModuleImport.cpp.
References convertValue(), mlir::m_Constant(), mlir::matchPattern(), mlir::succeeded(), and mlir::success().
matchLocalVariableAttr()
DILocalVariableAttr ModuleImport::matchLocalVariableAttr (llvm::Value * value)
Converts value to a local variable attribute.
Asserts if the matching fails.
Definition at line 1120 of file ModuleImport.cpp.
processFunction()
LogicalResult ModuleImport::processFunction (llvm::Function * func)
Imports func into the current module.
Definition at line 1557 of file ModuleImport.cpp.
References convertType(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::emitWarning(), mlir::LLVMImportInterface::isConvertibleIntrinsic(), processFunctionAttributes(), mlir::OpBuilder::setInsertionPoint(), and mlir::success().
Referenced by convertFunctions().
processFunctionAttributes()
void ModuleImport::processFunctionAttributes (llvm::Function * func, LLVMFuncOp funcOp)
Converts function attributes of LLVM Function func into LLVM dialect attributes of LLVMFuncOp funcOp.
Definition at line 1512 of file ModuleImport.cpp.
References processMemoryEffects(), and processPassthroughAttrs().
Referenced by processFunction().
setFastmathFlagsAttr()
void ModuleImport::setFastmathFlagsAttr (llvm::Instruction * inst, Operation * op) const
Sets the fastmath flags attribute for the imported operation op given the original instruction inst.
Asserts if the operation does not implement the fastmath interface.
Definition at line 599 of file ModuleImport.cpp.
translateLoc()
Location ModuleImport::translateLoc (llvm::DILocation * loc)
Translates the debug location.
Definition at line 1133 of file ModuleImport.cpp.
Referenced by convertValue().
translateLoopAnnotationAttr()
LoopAnnotationAttr ModuleImport::translateLoopAnnotationAttr (const llvm::MDNode * node, Location loc) const
Returns the loop annotation attribute that corresponds to the given LLVM loop metadata node.
Definition at line 1664 of file ModuleImport.cpp.
The documentation for this class was generated from the following files:
include/mlir/Target/LLVMIR/ModuleImport.h
lib/Target/LLVMIR/ModuleImport.cpp