MLIR: mlir::LLVM::ModuleTranslation Class Reference
mlir::LLVM::ModuleTranslation Class Reference
Implementation class for module translation.
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
Classes
struct SaveStack
RAII object calling stackPush/stackPop on construction/destruction.
class StackFrame
Common CRTP base class for ModuleTranslation stack frames.
class StackFrameBase
Concrete CRTP base class for ModuleTranslation stack frames.
Public Member Functions
void mapFunction (StringRef name, llvm::Function *func)
Stores the mapping between a function name and its LLVM IR representation.
llvm::Function * lookupFunction (StringRef name) const
Finds an LLVM IR function by its name.
void mapValue (Value mlir, llvm::Value *llvm)
Stores the mapping between an MLIR value and its LLVM IR counterpart.
llvm::Value *& mapValue (Value value)
Provides write-once access to store the LLVM IR value corresponding to the given MLIR value.
llvm::Value * lookupValue (Value value) const
Finds an LLVM IR value corresponding to the given MLIR value.
SmallVector< llvm::Value * > lookupValues (ValueRange values)
Looks up remapped a list of remapped values.
void mapBlock (Block *mlir, llvm::BasicBlock *llvm)
Stores the mapping between an MLIR block and LLVM IR basic block.
llvm::BasicBlock * lookupBlock (Block *block) const
Finds an LLVM IR basic block that corresponds to the given MLIR block.
void mapBranch (Operation *mlir, llvm::Instruction *llvm)
Stores the mapping between an MLIR operation with successors and a corresponding LLVM IR instruction.
llvm::Instruction * lookupBranch (Operation *op) const
Finds an LLVM IR instruction that corresponds to the given MLIR operation with successors.
void forgetMapping (Region &region)
Removes the mapping for blocks contained in the region and values defined in these blocks.
llvm::MDNode * getAliasScope (Operation *op, SymbolRefAttr aliasScopeRef) const
Returns the LLVM metadata corresponding to a symbol reference to an mlir LLVM dialect alias scope operation.
llvm::MDNode * getAliasScopes (Operation *op, ArrayRef< SymbolRefAttr > aliasScopeRefs) const
Returns the LLVM metadata corresponding to an array of symbol references to mlir LLVM dialect alias scope operations.
void setAccessGroupsMetadata (AccessGroupOpInterface op, llvm::Instruction *inst)
void setAliasScopeMetadata (AliasAnalysisOpInterface op, llvm::Instruction *inst)
void setTBAAMetadata (AliasAnalysisOpInterface op, llvm::Instruction *inst)
Sets LLVM TBAA metadata for memory operations that have TBAA attributes.
void setLoopMetadata (Operation *op, llvm::Instruction *inst)
Sets LLVM loop metadata for branch operations that have a loop annotation attribute.
llvm::Type * convertType (Type type)
Converts the type from MLIR LLVM dialect to LLVM.
MLIRContext & getContext ()
Returns the MLIR context of the module being translated.
llvm::LLVMContext & getLLVMContext () const
Returns the LLVM context in which the IR is being constructed.
llvm::GlobalValue * lookupGlobal (Operation *op)
Finds an LLVM IR global value that corresponds to the given MLIR operation defining a global value.
llvm::OpenMPIRBuilder * getOpenMPBuilder ()
Returns the OpenMP IR builder associated with the LLVM IR module being constructed.
llvm::Module * getLLVMModule ()
Returns the LLVM module in which the IR is being constructed.
const llvm::DILocation * translateLoc (Location loc, llvm::DILocalScope *scope)
Translates the given location.
llvm::Metadata * translateDebugInfo (LLVM::DINodeAttr attr)
Translates the given LLVM debug info metadata.
LogicalResult convertBlock (Block &bb, bool ignoreArguments, llvm::IRBuilderBase &builder)
Translates the contents of the given block to LLVM IR using this translator.
llvm::NamedMDNode * getOrInsertNamedModuleMetadata (StringRef name)
Gets the named metadata in the LLVM IR module being constructed, creating it if it does not exist.
template<typename T , typename... Args>
void stackPush (Args &&...args)
Creates a stack frame of type T on ModuleTranslation stack.
void stackPop ()
Pops the last element from the ModuleTranslation stack.
template<typename T >
WalkResult stackWalk (llvm::function_ref< WalkResult(const T &)> callback) const
Calls callback for every ModuleTranslation stack frame of type T starting from the top of the stack.
SymbolTableCollection & symbolTable ()
Friends
std::unique_ptr< llvm::Module > mlir::translateModuleToLLVMIR (Operation *, llvm::LLVMContext &, StringRef)
Detailed Description
Implementation class for module translation.
Holds a reference to the module being translated, and the mappings between the original and the translated functions, basic blocks and values. It is practically easier to hold these mappings in one class since the conversion of control flow operations needs to look up block and function mappings.
Definition at line 55 of file ModuleTranslation.h.
Member Function Documentation
convertBlock()
LogicalResult ModuleTranslation::convertBlock (Block & bb, bool ignoreArguments, llvm::IRBuilderBase & builder)
Translates the contents of the given block to LLVM IR using this translator.
Convert block to LLVM IR.
The LLVM IR basic block corresponding to the given block is expected to exist in the mapping of this translator. Uses builder to translate the IR, leaving it at the end of the block. If ignoreArguments is set, does not produce PHI nodes for the block arguments. Otherwise, the PHI nodes are constructed for block arguments but are not connected to the predecessors that may not exist yet.
Unless ignoreArguments is set, emit PHI nodes to define values corresponding to the MLIR block arguments. These nodes are not connected to the source basic blocks, which may not exist yet. Uses builder to construct the LLVM IR. Expects the LLVM IR basic block to have been created for bb and included in the block mapping. Inserts new instructions at the end of the block and leaves builder in a state suitable for further insertion into the end of the block.
Definition at line 615 of file ModuleTranslation.cpp.
References convertType(), mlir::emitError(), mlir::Block::front(), mlir::Block::getArguments(), mlir::Operation::getLoc(), mlir::Block::getPredecessors(), mlir::LLVM::isCompatibleType(), lookupBlock(), and mapValue().
Referenced by convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpOpRegions(), and inlineConvertOmpRegions().
convertType()
llvm::Type * ModuleTranslation::convertType (Type type)
Converts the type from MLIR LLVM dialect to LLVM.
Definition at line 1246 of file ModuleTranslation.cpp.
References mlir::LLVM::TypeToLLVMIRTranslator::translateType().
Referenced by convertBlock(), convertOmpAtomicCapture(), convertOmpAtomicRead(), convertOmpAtomicUpdate(), convertOmpAtomicWrite(), convertOmpOpRegions(), convertOmpReductionOp(), convertOmpWsLoop(), and convertOperationImpl().
forgetMapping()
void ModuleTranslation::forgetMapping (Region & region)
Removes the mapping for blocks contained in the region and values defined in these blocks.
Definition at line 459 of file ModuleTranslation.cpp.
Referenced by convertOmpOpRegions(), and inlineConvertOmpRegions().
getAliasScope()
llvm::MDNode * ModuleTranslation::getAliasScope (Operation * op, SymbolRefAttr aliasScopeRef) const
Returns the LLVM metadata corresponding to a symbol reference to an mlir LLVM dialect alias scope operation.
Definition at line 1074 of file ModuleTranslation.cpp.
getAliasScopes()
llvm::MDNode * ModuleTranslation::getAliasScopes (Operation * op, ArrayRef< SymbolRefAttr > aliasScopeRefs) const
Returns the LLVM metadata corresponding to an array of symbol references to mlir LLVM dialect alias scope operations.
Definition at line 1085 of file ModuleTranslation.cpp.
getContext()
MLIRContext& mlir::LLVM::ModuleTranslation::getContext () inline
Returns the MLIR context of the module being translated.
Definition at line 152 of file ModuleTranslation.h.
References mlir::Operation::getContext().
Referenced by convertOperationImpl().
getLLVMContext()
llvm::LLVMContext& mlir::LLVM::ModuleTranslation::getLLVMContext () const inline
Returns the LLVM context in which the IR is being constructed.
Definition at line 155 of file ModuleTranslation.h.
Referenced by convertBranchWeights(), convertOmpCritical(), convertOperationImpl(), and mlir::LLVM::detail::getLLVMConstant().
getLLVMModule()
llvm::Module* mlir::LLVM::ModuleTranslation::getLLVMModule () inline
Returns the LLVM module in which the IR is being constructed.
Definition at line 168 of file ModuleTranslation.h.
getOpenMPBuilder()
llvm::OpenMPIRBuilder * ModuleTranslation::getOpenMPBuilder ()
Returns the OpenMP IR builder associated with the LLVM IR module being constructed.
Definition at line 1259 of file ModuleTranslation.cpp.
Referenced by convertOmpAtomicCapture(), convertOmpAtomicRead(), convertOmpAtomicUpdate(), convertOmpAtomicWrite(), convertOmpCritical(), convertOmpMaster(), convertOmpOrdered(), convertOmpOrderedRegion(), convertOmpParallel(), convertOmpSimdLoop(), convertOmpSingle(), convertOmpTarget(), convertOmpTaskgroupOp(), convertOmpTaskOp(), convertOmpThreadprivate(), convertOmpWsLoop(), and processMapOperand().
getOrInsertNamedModuleMetadata()
llvm::NamedMDNode * ModuleTranslation::getOrInsertNamedModuleMetadata (StringRef name)
Gets the named metadata in the LLVM IR module being constructed, creating it if it does not exist.
Definition at line 1289 of file ModuleTranslation.cpp.
lookupBlock()
llvm::BasicBlock* mlir::LLVM::ModuleTranslation::lookupBlock (Block * block) const inline
Finds an LLVM IR basic block that corresponds to the given MLIR block.
Definition at line 101 of file ModuleTranslation.h.
Referenced by mlir::LLVM::detail::connectPHINodes(), convertBlock(), convertOmpOpRegions(), and convertOperationImpl().
lookupBranch()
llvm::Instruction* mlir::LLVM::ModuleTranslation::lookupBranch (Operation * op) const inline
Finds an LLVM IR instruction that corresponds to the given MLIR operation with successors.
Definition at line 116 of file ModuleTranslation.h.
Referenced by mlir::LLVM::detail::connectPHINodes().
lookupFunction()
llvm::Function* mlir::LLVM::ModuleTranslation::lookupFunction (StringRef name) const inline
Finds an LLVM IR function by its name.
Definition at line 69 of file ModuleTranslation.h.
Referenced by convertOperationImpl(), and mlir::LLVM::detail::getLLVMConstant().
lookupGlobal()
llvm::GlobalValue* mlir::LLVM::ModuleTranslation::lookupGlobal (Operation * op) inline
Finds an LLVM IR global value that corresponds to the given MLIR operation defining a global value.
Definition at line 159 of file ModuleTranslation.h.
Referenced by convertOmpThreadprivate(), and convertOperationImpl().
lookupValue()
llvm::Value* mlir::LLVM::ModuleTranslation::lookupValue (Value value) const inline
Finds an LLVM IR value corresponding to the given MLIR value.
Definition at line 86 of file ModuleTranslation.h.
Referenced by mlir::LLVM::detail::connectPHINodes(), convertOmpAtomicCapture(), convertOmpAtomicRead(), convertOmpAtomicUpdate(), convertOmpAtomicWrite(), convertOmpOpRegions(), convertOmpParallel(), convertOmpReductionOp(), convertOmpSimdLoop(), convertOmpTarget(), convertOmpTaskOp(), convertOmpWsLoop(), convertOperationImpl(), lookupValues(), and processMapOperand().
lookupValues()
SmallVector< llvm::Value * > ModuleTranslation::lookupValues (ValueRange values)
Looks up remapped a list of remapped values.
A helper to look up remapped operands in the value remapping table.
Definition at line 1251 of file ModuleTranslation.cpp.
References lookupValue().
Referenced by convertOmpOrdered(), convertOperationImpl(), and inlineConvertOmpRegions().
mapBlock()
void mlir::LLVM::ModuleTranslation::mapBlock (Block * mlir, llvm::BasicBlock * llvm) inline
Stores the mapping between an MLIR block and LLVM IR basic block.
Definition at line 94 of file ModuleTranslation.h.
Referenced by convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpOpRegions(), and inlineConvertOmpRegions().
mapBranch()
void mlir::LLVM::ModuleTranslation::mapBranch (Operation * mlir, llvm::Instruction * llvm) inline
Stores the mapping between an MLIR operation with successors and a corresponding LLVM IR instruction.
Definition at line 107 of file ModuleTranslation.h.
Referenced by convertOperationImpl().
mapFunction()
void mlir::LLVM::ModuleTranslation::mapFunction (StringRef name, llvm::Function * func) inline
Stores the mapping between a function name and its LLVM IR representation.
Definition at line 61 of file ModuleTranslation.h.
mapValue() [1/2]
void mlir::LLVM::ModuleTranslation::mapValue (Value mlir, llvm::Value * llvm) inline
Stores the mapping between an MLIR value and its LLVM IR counterpart.
Definition at line 74 of file ModuleTranslation.h.
References mapValue().
Referenced by convertBlock(), convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpReductionOp(), convertOmpSimdLoop(), convertOmpThreadprivate(), convertOmpWsLoop(), convertOperationImpl(), makeAtomicReductionGen(), makeReductionGen(), and mapValue().
mapValue() [2/2]
llvm::Value*& mlir::LLVM::ModuleTranslation::mapValue (Value value) inline
Provides write-once access to store the LLVM IR value corresponding to the given MLIR value.
Definition at line 78 of file ModuleTranslation.h.
setAccessGroupsMetadata()
void ModuleTranslation::setAccessGroupsMetadata (AccessGroupOpInterface op, llvm::Instruction * inst)
Definition at line 1030 of file ModuleTranslation.cpp.
setAliasScopeMetadata()
void ModuleTranslation::setAliasScopeMetadata (AliasAnalysisOpInterface op, llvm::Instruction * inst)
Definition at line 1094 of file ModuleTranslation.cpp.
setLoopMetadata()
void ModuleTranslation::setLoopMetadata (Operation * op, llvm::Instruction * inst)
Sets LLVM loop metadata for branch operations that have a loop annotation attribute.
Definition at line 1233 of file ModuleTranslation.cpp.
Referenced by convertOperationImpl().
setTBAAMetadata()
void ModuleTranslation::setTBAAMetadata (AliasAnalysisOpInterface op, llvm::Instruction * inst)
Sets LLVM TBAA metadata for memory operations that have TBAA attributes.
Definition at line 1120 of file ModuleTranslation.cpp.
stackPop()
void mlir::LLVM::ModuleTranslation::stackPop () inline
Pops the last element from the ModuleTranslation stack.
Definition at line 231 of file ModuleTranslation.h.
Referenced by mlir::LLVM::ModuleTranslation::SaveStack< T >::~SaveStack().
stackPush()
template<typename T , typename... Args> void mlir::LLVM::ModuleTranslation::stackPush (Args &&... args) inline
Creates a stack frame of type T on ModuleTranslation stack.
T must be derived from StackFrameBase<T> and constructible from the provided arguments. Doing this before entering the region of the op being translated makes the frame available when translating ops within that region.
Definition at line 223 of file ModuleTranslation.h.
Referenced by mlir::LLVM::ModuleTranslation::SaveStack< T >::SaveStack().
stackWalk()
template<typename T > WalkResult mlir::LLVM::ModuleTranslation::stackWalk (llvm::function_ref< WalkResult(const T &)> callback) const inline
Calls callback for every ModuleTranslation stack frame of type T starting from the top of the stack.
Definition at line 237 of file ModuleTranslation.h.
References mlir::WalkResult::advance(), mlir::WalkResult::skip(), and mlir::WalkResult::wasInterrupted().
Referenced by convertOmpReductionOp(), and findAllocaInsertPoint().
symbolTable()
SymbolTableCollection& mlir::LLVM::ModuleTranslation::symbolTable () inline
Definition at line 266 of file ModuleTranslation.h.
Referenced by convertOmpThreadprivate(), and convertOperationImpl().
translateDebugInfo()
llvm::Metadata * ModuleTranslation::translateDebugInfo (LLVM::DINodeAttr attr)
Translates the given LLVM debug info metadata.
Definition at line 1284 of file ModuleTranslation.cpp.
translateLoc()
const llvm::DILocation * ModuleTranslation::translateLoc (Location loc, llvm::DILocalScope * scope)
Translates the given location.
Definition at line 1280 of file ModuleTranslation.cpp.
Friends And Related Function Documentation
mlir::translateModuleToLLVMIR
std::unique_ptr<llvm::Module> mlir::translateModuleToLLVMIR (Operation * , llvm::LLVMContext & , StringRef) friend
The documentation for this class was generated from the following files:
include/mlir/Target/LLVMIR/ModuleTranslation.h
lib/Target/LLVMIR/ModuleTranslation.cpp