MLIR: mlir::TypeConverter Class Reference
mlir::TypeConverter Class Reference
Type conversion class.
#include "mlir/Transforms/DialectConversion.h"
Classes
class AttributeConversionResult
The general result of a type attribute conversion callback, allowing for early termination.
class SignatureConversion
This class provides all of the information necessary to convert a type signature.
Public Member Functions
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<0>>
void addConversion (FnT &&callback)
Register a conversion function.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addArgumentMaterialization (FnT &&callback)
Register a materialization function, which must be convertible to the following form: std::optional<Value>(OpBuilder &, T, ValueRange, Location), where T is any subclass of Type.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addSourceMaterialization (FnT &&callback)
This method registers a materialization that will be called when converting a legal type to an illegal source type.
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>>
void addTargetMaterialization (FnT &&callback)
This method registers a materialization that will be called when converting type from an illegal, or source, type to a legal type.
template<typename FnT , typename T = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<0>, typename A = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<1>>
void addTypeAttributeConversion (FnT &&callback)
Register a conversion function for attributes within types.
LogicalResult convertType (Type t, SmallVectorImpl< Type > &results)
Convert the given type.
Type convertType (Type t)
This hook simplifies defining 1-1 type conversions.
template<typename TargetType >
TargetType convertType (Type t)
Attempts a 1-1 type conversion, expecting the result type to be TargetType.
LogicalResult convertTypes (TypeRange types, SmallVectorImpl< Type > &results)
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
template<typename RangeT >
std::enable_if_t<!std::is_convertible< RangeT, Type >::value &&!std::is_convertible< RangeT, Operation * >::value, bool > isLegal (RangeT &&range)
Return true if all of the given types are legal for this type converter.
bool isLegal (Operation *op)
Return true if the given operation has legal operand and result types.
bool isLegal (Region *region)
Return true if the types of block arguments within the region are legal.
bool isSignatureLegal (FunctionType ty)
Return true if the inputs and outputs of the given function type are legal.
LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result)
This method allows for converting a specific argument of a signature.
LogicalResult convertSignatureArgs (TypeRange types, SignatureConversion &result, unsigned origInputOffset=0)
std::optional< SignatureConversion > convertBlockSignature (Block *block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
Value materializeArgumentConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs)
Materialize a conversion from a set of types into one result type by generating a cast sequence of some kind.
Value materializeSourceConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs)
Value materializeTargetConversion (OpBuilder &builder, Location loc, Type resultType, ValueRange inputs)
std::optional< Attribute > convertTypeAttribute (Type type, Attribute attr)
Convert an attribute present attr from within the type type using the registered conversion functions.
Detailed Description
Type conversion class.
Specific conversions and materializations can be registered using addConversion and addMaterialization, respectively.
Definition at line 38 of file DialectConversion.h.
Member Function Documentation
addArgumentMaterialization()
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>> void mlir::TypeConverter::addArgumentMaterialization (FnT && callback) inline
Register a materialization function, which must be convertible to the following form: std::optional<Value>(OpBuilder &, T, ValueRange, Location), where T is any subclass of Type.
This function is responsible for creating an operation, using the OpBuilder and Location provided, that "casts" a range of values into a single value of the given type T. It must return a Value of the converted type on success, an std::nullopt if it failed but other materialization can be attempted, and nullptr on unrecoverable failure. It will only be called for (sub)types of T. Materialization functions must be provided when a type conversion may persist after the conversion has finished.
This method registers a materialization that will be called when converting an illegal block argument type, to a legal type.
Definition at line 166 of file DialectConversion.h.
Referenced by mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter(), and mlir::LLVMTypeConverter::LLVMTypeConverter().
addConversion()
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<0>> void mlir::TypeConverter::addConversion (FnT && callback) inline
Register a conversion function.
A conversion function must be convertible to any of the following forms(where T is a class derived from Type:
std::optional<Type>(T)
This form represents a 1-1 type conversion. It should return nullptr or std::nullopt to signify failure. If std::nullopt is returned, the converter is allowed to try another conversion function to perform the conversion.
std::optional<LogicalResult>(T, SmallVectorImpl<Type> &)
This form represents a 1-N type conversion. It should return failure or std::nullopt to signify a failed conversion. If the new set of types is empty, the type is removed and any usages of the existing value are expected to be removed during conversion. If std::nullopt is returned, the converter is allowed to try another conversion function to perform the conversion.
std::optional<LogicalResult>(T, SmallVectorImpl<Type> &, ArrayRef<Type>)
This form represents a 1-N type conversion supporting recursive types. The first two arguments and the return value are the same as for the regular 1-N form. The third argument is contains is the "call stack" of the recursive conversion: it contains the list of types currently being converted, with the current type being the last one. If it is present more than once in the list, the conversion concerns a recursive type. Note: When attempting to convert a type, e.g. via 'convertType', the mostly recently added conversions will be invoked first.
Definition at line 146 of file DialectConversion.h.
Referenced by mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter(), mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::spirv::MemorySpaceToStorageClassConverter::MemorySpaceToStorageClassConverter(), mlir::populateAMDGPUToROCDLConversionPatterns(), mlir::populateAsyncStructuralTypeConversionsAndLegality(), mlir::populateGpuToLLVMConversionPatterns(), mlir::memref::populateMemRefWideIntEmulationConversions(), mlir::populateSPIRVToLLVMTypeConversion(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), and mlir::arith::WideIntEmulationConverter::WideIntEmulationConverter().
addSourceMaterialization()
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>> void mlir::TypeConverter::addSourceMaterialization (FnT && callback) inline
This method registers a materialization that will be called when converting a legal type to an illegal source type.
This is used when conversions to an illegal type must persist beyond the main conversion.
Definition at line 175 of file DialectConversion.h.
Referenced by mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter(), and mlir::LLVMTypeConverter::LLVMTypeConverter().
addTargetMaterialization()
template<typename FnT , typename T = typename llvm::function_traits< std::decay_t<FnT>>::template arg_t<1>> void mlir::TypeConverter::addTargetMaterialization (FnT && callback) inline
This method registers a materialization that will be called when converting type from an illegal, or source, type to a legal type.
Definition at line 183 of file DialectConversion.h.
Referenced by mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter(), and mlir::LLVMTypeConverter::LLVMTypeConverter().
addTypeAttributeConversion()
template<typename FnT , typename T = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<0>, typename A = typename llvm::function_traits<std::decay_t<FnT>>::template arg_t<1>> void mlir::TypeConverter::addTypeAttributeConversion (FnT && callback) inline
Register a conversion function for attributes within types.
Type converters may call this function in order to allow hoking into the translation of attributes that exist within types. For example, a type converter for the memref type could use these conversions to convert memory spaces or layouts in an extensible way.
The conversion functions take a non-null Type or subclass of Type and a non-null Attribute (or subclass of Attribute), and returns a AttributeConversionResult. This result can either contan an Attribute, which may be nullptr, representing the conversion's success, AttributeConversionResult::na() (the default empty value), indicating that the conversion function did not apply and that further conversion functions should be checked, or AttributeConversionResult::abort() indicating that the conversion process should be aborted.
Registered conversion functions are callled in the reverse of the order in which they were registered.
Definition at line 211 of file DialectConversion.h.
Referenced by mlir::LLVMTypeConverter::LLVMTypeConverter(), and mlir::populateGpuMemorySpaceAttributeConversions().
convertBlockSignature()
auto TypeConverter::convertBlockSignature (Block * block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
This function should return a valid conversion for the signature on success, std::nullopt otherwise.
Definition at line 3005 of file DialectConversion.cpp.
References convertSignatureArgs(), mlir::failed(), mlir::Block::getArgumentTypes(), and mlir::Block::getNumArguments().
convertSignatureArg()
LogicalResult TypeConverter::convertSignatureArg (unsigned inputNo, Type type, SignatureConversion & result)
This method allows for converting a specific argument of a signature.
It takes as inputs the original argument input number, type. On success, it populates 'result' with any new mappings.
Definition at line 2972 of file DialectConversion.cpp.
References mlir::TypeConverter::SignatureConversion::addInputs(), convertType(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by convertSignatureArgs().
convertSignatureArgs()
LogicalResult TypeConverter::convertSignatureArgs (TypeRange types, SignatureConversion & result, unsigned origInputOffset = 0)
Definition at line 2987 of file DialectConversion.cpp.
References convertSignatureArg(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by mlir::OneToNTypeConverter::computeTypeMapping(), convertBlockSignature(), and convertFuncOpTypes().
convertType() [1/3]
Type TypeConverter::convertType (Type t)
This hook simplifies defining 1-1 type conversions.
This function returns the type to convert to on success, and a null type on failure.
Definition at line 2939 of file DialectConversion.cpp.
References convertType(), and mlir::failed().
convertType() [2/3]
template<typename TargetType > TargetType mlir::TypeConverter::convertType (Type t) inline
Attempts a 1-1 type conversion, expecting the result type to be TargetType.
Returns the converted type cast to TargetType on success, and a null type on conversion or cast failure.
Definition at line 230 of file DialectConversion.h.
References convertType().
convertType() [3/3]
LogicalResult TypeConverter::convertType (Type t, SmallVectorImpl< Type > & results)
Convert the given type.
This function should return failure if no valid conversion exists, success otherwise. If the new set of types is empty, the type is removed and any usages of the existing value are expected to be removed during conversion.
Definition at line 2901 of file DialectConversion.cpp.
References mlir::failure(), mlir::succeeded(), and mlir::success().
Referenced by convertArrayType(), convertRuntimeArrayType(), convertSignatureArg(), convertType(), convertTypes(), mlir::ConvertToLLVMPattern::createMemRefDescriptor(), mlir::ConvertToLLVMPattern::getElementPtrType(), mlir::ConvertToLLVMPattern::getMemRefDescriptorSizes(), mlir::ConvertToLLVMPattern::getSizeInBytes(), mlir::ConvertToLLVMPattern::isConvertibleAndHasIdentityMaps(), isLegal(), lowerAsEntryFunction(), mlir::GPUFuncOpLowering::matchAndRewrite(), mlir::GPUPrintfOpToHIPLowering::matchAndRewrite(), mlir::GPUPrintfOpToLLVMCallLowering::matchAndRewrite(), mlir::GPUPrintfOpToVPrintfLowering::matchAndRewrite(), mlir::spirv::MemorySpaceToStorageClassConverter::MemorySpaceToStorageClassConverter(), mlir::populateAsyncStructuralTypeConversionsAndLegality(), mlir::memref::populateMemRefWideIntEmulationConversions(), mlir::registerConversionPDLFunctions(), and mlir::detail::ConversionPatternRewriterImpl::remapValues().
convertTypeAttribute()
std::optional< Attribute > TypeConverter::convertTypeAttribute (Type type, Attribute attr)
Convert an attribute present attr from within the type type using the registered conversion functions.
If no applicable conversion has been registered, return std::nullopt. Note that the empty attribute/nullptr is a valid return value for this function.
Definition at line 3048 of file DialectConversion.cpp.
References mlir::TypeConverter::AttributeConversionResult::getResult(), mlir::TypeConverter::AttributeConversionResult::hasResult(), and mlir::TypeConverter::AttributeConversionResult::isAbort().
Referenced by mlir::LLVMTypeConverter::getMemRefAddressSpace().
convertTypes()
LogicalResult TypeConverter::convertTypes (TypeRange types, SmallVectorImpl< Type > & results)
Convert the given set of types, filling 'results' as necessary.
This returns failure if the conversion of any of the types fails, success otherwise.
Definition at line 2949 of file DialectConversion.cpp.
References convertType(), mlir::failed(), mlir::failure(), and mlir::success().
Referenced by convertFuncOpTypes(), mlir::LLVMTypeConverter::LLVMTypeConverter(), mlir::registerConversionPDLFunctions(), and mlir::arith::WideIntEmulationConverter::WideIntEmulationConverter().
isLegal() [1/4]
bool TypeConverter::isLegal (Operation * op)
Return true if the given operation has legal operand and result types.
Definition at line 2958 of file DialectConversion.cpp.
isLegal() [2/4]
template<typename RangeT > std::enable_if_t<!std::is_convertible<RangeT, Type>::value && !std::is_convertible<RangeT, Operation *>::value, bool> mlir::TypeConverter::isLegal (RangeT && range) inline
Return true if all of the given types are legal for this type converter.
Definition at line 247 of file DialectConversion.h.
References isLegal().
isLegal() [3/4]
bool TypeConverter::isLegal (Region * region)
Return true if the types of block arguments within the region are legal.
Definition at line 2962 of file DialectConversion.cpp.
References mlir::Block::getArgumentTypes(), and isLegal().
isLegal() [4/4]
bool TypeConverter::isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
the type converts to itself.
Definition at line 2957 of file DialectConversion.cpp.
References convertType().
Referenced by isLegal(), and isSignatureLegal().
isSignatureLegal()
bool TypeConverter::isSignatureLegal (FunctionType ty)
Return true if the inputs and outputs of the given function type are legal.
Definition at line 2968 of file DialectConversion.cpp.
References isLegal().
materializeArgumentConversion()
Value mlir::TypeConverter::materializeArgumentConversion (OpBuilder & builder, Location loc, Type resultType, ValueRange inputs) inline
Materialize a conversion from a set of types into one result type by generating a cast sequence of some kind.
See the respective add*Materialization for more information on the context for these methods.
Definition at line 278 of file DialectConversion.h.
materializeSourceConversion()
Value mlir::TypeConverter::materializeSourceConversion (OpBuilder & builder, Location loc, Type resultType, ValueRange inputs) inline
Definition at line 283 of file DialectConversion.h.
materializeTargetConversion()
Value mlir::TypeConverter::materializeTargetConversion (OpBuilder & builder, Location loc, Type resultType, ValueRange inputs) inline
Definition at line 288 of file DialectConversion.h.
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/Utils/DialectConversion.cpp