MLIR: mlir::tblgen::Property Class Reference
mlir::tblgen::Property Class Reference
#include "mlir/TableGen/Property.h"
Public Member Functions
Property (const llvm::Record *record)
Property (const llvm::DefInit *init)
StringRef getStorageType () const
StringRef getInterfaceType () const
StringRef getConvertFromStorageCall () const
StringRef getAssignToStorageCall () const
StringRef getConvertToAttributeCall () const
StringRef getConvertFromAttributeCall () const
StringRef getHashPropertyCall () const
bool hasDefaultValue () const
StringRef getDefaultValue () const
const llvm::Record & getDef () const
Detailed Description
Definition at line 34 of file Property.h.
Constructor & Destructor Documentation
Property() [1/2]
mlir::tblgen::Property::Property (const llvm::Record * record) explicit
Property() [2/2]
mlir::tblgen::Property::Property (const llvm::DefInit * init) explicit
Member Function Documentation
getAssignToStorageCall()
StringRef Property::getAssignToStorageCall () const
Definition at line 60 of file Property.cpp.
References getValueAsString().
getConvertFromAttributeCall()
StringRef Property::getConvertFromAttributeCall () const
Definition at line 70 of file Property.cpp.
References getValueAsString().
getConvertFromStorageCall()
StringRef Property::getConvertFromStorageCall () const
Definition at line 55 of file Property.cpp.
References getValueAsString().
getConvertToAttributeCall()
StringRef Property::getConvertToAttributeCall () const
Definition at line 65 of file Property.cpp.
References getValueAsString().
getDef()
const llvm::Record & Property::getDef () const
Definition at line 86 of file Property.cpp.
getDefaultValue()
StringRef Property::getDefaultValue () const
Definition at line 81 of file Property.cpp.
References getValueAsString().
Referenced by hasDefaultValue().
getHashPropertyCall()
StringRef Property::getHashPropertyCall () const
Definition at line 75 of file Property.cpp.
References getValueAsString().
getInterfaceType()
StringRef Property::getInterfaceType () const
Definition at line 50 of file Property.cpp.
References getValueAsString().
getStorageType()
StringRef Property::getStorageType () const
Definition at line 42 of file Property.cpp.
References getValueAsString().
hasDefaultValue()
bool Property::hasDefaultValue () const
Definition at line 79 of file Property.cpp.
References getDefaultValue().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Property.h
lib/TableGen/Property.cpp