MLIR: mlir::LLVM::detail::LoopAnnotationImporter Class Reference
mlir::LLVM::detail::LoopAnnotationImporter Class Reference
A helper class that converts llvm.loop metadata nodes into corresponding LoopAnnotationAttrs and llvm.access.group nodes into AccessGroupMetadataOps.
#include "Target/LLVMIR/LoopAnnotationImporter.h"
Public Member Functions
LoopAnnotationImporter (OpBuilder &builder)
LoopAnnotationAttr translateLoopAnnotation (const llvm::MDNode *node, Location loc)
LogicalResult translateAccessGroup (const llvm::MDNode *node, Location loc, MetadataOp metadataOp)
Converts all LLVM access groups starting from node to MLIR access group operations mested in the region of metadataOp.
FailureOr< SmallVector< SymbolRefAttr > > lookupAccessGroupAttrs (const llvm::MDNode *node) const
Returns the symbol references pointing to the access group operations that map to the access group nodes starting from the access group metadata node.
Detailed Description
A helper class that converts llvm.loop metadata nodes into corresponding LoopAnnotationAttrs and llvm.access.group nodes into AccessGroupMetadataOps.
Definition at line 27 of file LoopAnnotationImporter.h.
Constructor & Destructor Documentation
LoopAnnotationImporter()
mlir::LLVM::detail::LoopAnnotationImporter::LoopAnnotationImporter (OpBuilder & builder) inline explicit
Definition at line 29 of file LoopAnnotationImporter.h.
Member Function Documentation
lookupAccessGroupAttrs()
FailureOr< SmallVector< SymbolRefAttr > > LoopAnnotationImporter::lookupAccessGroupAttrs (const llvm::MDNode * node) const
Returns the symbol references pointing to the access group operations that map to the access group nodes starting from the access group metadata node.
Returns failure, if any of the symbol references cannot be found.
Definition at line 495 of file LoopAnnotationImporter.cpp.
References mlir::failure().
translateAccessGroup()
LogicalResult LoopAnnotationImporter::translateAccessGroup (const llvm::MDNode * node, Location loc, MetadataOp metadataOp)
Converts all LLVM access groups starting from node to MLIR access group operations mested in the region of metadataOp.
It stores a mapping from every nested access group nod to the symbol pointing to the translated operation. Returns success if all conversions succeed and failure otherwise.
Definition at line 460 of file LoopAnnotationImporter.cpp.
References mlir::OpBuilder::create(), mlir::emitWarning(), mlir::failure(), mlir::get(), mlir::FlatSymbolRefAttr::get(), mlir::Builder::getContext(), mlir::OpBuilder::setInsertionPointToEnd(), and mlir::success().
translateLoopAnnotation()
LoopAnnotationAttr LoopAnnotationImporter::translateLoopAnnotation (const llvm::MDNode * node, Location loc)
Definition at line 443 of file LoopAnnotationImporter.cpp.
The documentation for this class was generated from the following files:
lib/Target/LLVMIR/LoopAnnotationImporter.h
lib/Target/LLVMIR/LoopAnnotationImporter.cpp