MLIR: mlir::sparse_tensor::CodegenEnv Class Reference
mlir::sparse_tensor::CodegenEnv Class Reference
The code generation environment class aggregates a number of data structures that are needed during the code generation phase of sparsification.
#include "Dialect/SparseTensor/Transforms/CodegenEnv.h"
Public Member Functions
CodegenEnv (linalg::GenericOp linop, SparsificationOptions opts, unsigned numTensors, unsigned numLoops, unsigned numFilterLoops, unsigned maxRank)
Constructs a code generation environment which can be passed around during sparsification for bookkeeping together with some consistency asserts.
LogicalResult initTensorExp ()
ExprId getExprId () const
linalg::GenericOp op () const
const SparsificationOptions & options () const
Merger & merger ()
LoopEmitter & emitter ()
void startEmit ()
std::optional< Operation * > genLoopBoundary (function_ref< std::optional< Operation * >(MutableArrayRef< Value > parameters)> callback)
Generates loop boundary statements (entering/exiting loops).
constexpr TensorId makeTensorId (unsigned t) const
constexpr LoopId makeLoopId (unsigned i) const
constexpr TensorLoopId makeTensorLoopId (unsigned t, unsigned i) const
const TensorExp & exp (ExprId e) const
const LatPoint & lat (LatPointId l) const
ArrayRef< LatPointId > set (LatSetId s) const
DimLevelType dlt (TensorId t, LoopId i) const
DimLevelType dlt (TensorLoopId b) const
TensorLevel makeTensorLevel (TensorId t, Level l) const
std::pair< TensorId, Level > unpackTensorLevel (TensorLevel tl) const
template<class ContainerTy >
auto unpackTensorLevelRange (ContainerTy &&c) const
bool isAdmissibleTensorExp (ExprId e)
Whether the tensor expression is admissible for codegen.
bool isAdmissibleTopoOrder ()
Whether the iteration graph is sorted in admissible topoOrder.
LoopOrd topSortSize () const
LoopId topSortAt (LoopOrd n) const
void topSortPushBack (LoopId i)
void topSortClear (size_t capacity=0)
ArrayRef< LoopId > getTopSortSlice (LoopOrd n, LoopOrd m) const
ArrayRef< LoopId > getLoopStackUpTo (LoopOrd n) const
ArrayRef< LoopId > getCurrentLoopStack () const
Value getLoopVar (LoopId i) const
Returns the induction-variable for the loop identified by the given LoopId.
bool hasSparseOutput () const
bool isSparseOutput (OpOperand *o) const
Value getInsertionChain () const
void updateInsertionChain (Value chain)
bool atExpandLevel (OpOperand *o, unsigned rank, LoopOrd n) const
void startExpand (Value values, Value filled, Value added, Value count)
bool isExpand () const
void updateExpandCount (Value count)
Value getExpandValues () const
Value getExpandFilled () const
Value getExpandAdded () const
Value getExpandCount () const
void endExpand ()
void startReduc (ExprId exp, Value val)
bool isReduc () const
void updateReduc (Value val)
Value getReduc () const
Value endReduc ()
void setValidLexInsert (Value val)
void clearValidLexInsert ()
Value getValidLexInsert () const
void startCustomReduc (ExprId exp)
bool isCustomReduc () const
Value getCustomRedId ()
void endCustomReduc ()
Detailed Description
The code generation environment class aggregates a number of data structures that are needed during the code generation phase of sparsification.
This environment simplifies passing around such data during sparsification (rather than passing around all the individual compoments where needed). Furthermore, it provides convience methods that keep implementation details transparent to sparsification while asserting on internal consistency.
Definition at line 35 of file CodegenEnv.h.
Constructor & Destructor Documentation
CodegenEnv()
CodegenEnv::CodegenEnv (linalg::GenericOp linop, SparsificationOptions opts, unsigned numTensors, unsigned numLoops, unsigned numFilterLoops, unsigned maxRank)
Constructs a code generation environment which can be passed around during sparsification for bookkeeping together with some consistency asserts.
Definition at line 52 of file CodegenEnv.cpp.
Member Function Documentation
atExpandLevel()
bool CodegenEnv::atExpandLevel (OpOperand * o, unsigned rank, LoopOrd n) const
Definition at line 251 of file CodegenEnv.cpp.
clearValidLexInsert()
void CodegenEnv::clearValidLexInsert ()
Definition at line 308 of file CodegenEnv.cpp.
References isReduc().
dlt() [1/2]
DimLevelType mlir::sparse_tensor::CodegenEnv::dlt (TensorId t, LoopId i) const inline
Definition at line 81 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::getDimLevelType().
Referenced by computeIterationGraph().
dlt() [2/2]
DimLevelType mlir::sparse_tensor::CodegenEnv::dlt (TensorLoopId b) const inline
Definition at line 84 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::getDimLevelType().
emitter()
LoopEmitter& mlir::sparse_tensor::CodegenEnv::emitter () inline
Definition at line 54 of file CodegenEnv.h.
Referenced by endLoop(), endLoopSeq(), genIf(), genSubscript(), genWhile(), startLoop(), and startLoopSeq().
endCustomReduc()
void CodegenEnv::endCustomReduc ()
Definition at line 323 of file CodegenEnv.cpp.
References isCustomReduc(), and mlir::sparse_tensor::detail::kInvalidId.
endExpand()
void CodegenEnv::endExpand ()
Definition at line 270 of file CodegenEnv.cpp.
endReduc()
Value CodegenEnv::endReduc ()
Definition at line 294 of file CodegenEnv.cpp.
References mlir::sparse_tensor::Merger::clearExprValue(), isReduc(), and mlir::sparse_tensor::detail::kInvalidId.
exp()
const TensorExp& mlir::sparse_tensor::CodegenEnv::exp (ExprId e) const inline
Definition at line 78 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::exp().
Referenced by genInvariants(), genInvariantValue(), genTensorLoad(), getCustomRedId(), isAdmissibleTensorExp(), startCustomReduc(), and startReduc().
genLoopBoundary()
std::optional< Operation * > CodegenEnv::genLoopBoundary (function_ref< std::optional< Operation * >(MutableArrayRef< Value > parameters)> callback)
Generates loop boundary statements (entering/exiting loops).
The function passes and updates the passed-in parameters.
Definition at line 118 of file CodegenEnv.cpp.
References isExpand(), isReduc(), setValidLexInsert(), updateExpandCount(), updateInsertionChain(), and updateReduc().
Referenced by endLoop(), and genWhile().
getCurrentLoopStack()
ArrayRef< LoopId > CodegenEnv::getCurrentLoopStack () const
Definition at line 227 of file CodegenEnv.cpp.
References mlir::sparse_tensor::LoopEmitter::getCurrentDepth(), and getLoopStackUpTo().
Referenced by isInvariantAffine().
getCustomRedId()
Value CodegenEnv::getCustomRedId ()
Definition at line 318 of file CodegenEnv.cpp.
References exp(), isCustomReduc(), and op().
getExpandAdded()
Value mlir::sparse_tensor::CodegenEnv::getExpandAdded () const inline
Definition at line 156 of file CodegenEnv.h.
getExpandCount()
Value mlir::sparse_tensor::CodegenEnv::getExpandCount () const inline
Definition at line 157 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), and genStmt().
getExpandFilled()
Value mlir::sparse_tensor::CodegenEnv::getExpandFilled () const inline
Definition at line 155 of file CodegenEnv.h.
getExpandValues()
Value mlir::sparse_tensor::CodegenEnv::getExpandValues () const inline
Definition at line 154 of file CodegenEnv.h.
getExprId()
ExprId mlir::sparse_tensor::CodegenEnv::getExprId () const inline
Definition at line 49 of file CodegenEnv.h.
getInsertionChain()
Value mlir::sparse_tensor::CodegenEnv::getInsertionChain () const inline
Definition at line 146 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genIf(), and genStmt().
getLoopStackUpTo()
ArrayRef< LoopId > CodegenEnv::getLoopStackUpTo (LoopOrd n) const
Definition at line 223 of file CodegenEnv.cpp.
Referenced by getCurrentLoopStack(), and permute().
getLoopVar()
Value CodegenEnv::getLoopVar (LoopId i) const
Returns the induction-variable for the loop identified by the given LoopId.
This method handles application of the topological sort in order to convert the LoopId into the corresponding LoopOrd.
Definition at line 231 of file CodegenEnv.cpp.
References mlir::sparse_tensor::LoopEmitter::getLoopIV(), and topSortSize().
Referenced by endLoopSeq(), genIf(), genIndex(), relinkBranch(), and startLoopSeq().
getReduc()
Value mlir::sparse_tensor::CodegenEnv::getReduc () const inline
Definition at line 167 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genIf(), and genStmt().
getTopSortSlice()
ArrayRef< LoopId > CodegenEnv::getTopSortSlice (LoopOrd n, LoopOrd m) const
Definition at line 219 of file CodegenEnv.cpp.
getValidLexInsert()
Value mlir::sparse_tensor::CodegenEnv::getValidLexInsert () const inline
Definition at line 171 of file CodegenEnv.h.
Referenced by endIf(), endLoop(), finalizeWhileOp(), and genIf().
hasSparseOutput()
bool mlir::sparse_tensor::CodegenEnv::hasSparseOutput () const inline
Definition at line 143 of file CodegenEnv.h.
Referenced by isAdmissibleTopoOrder(), and isParallelFor().
initTensorExp()
LogicalResult CodegenEnv::initTensorExp ()
Definition at line 62 of file CodegenEnv.cpp.
References mlir::sparse_tensor::Merger::buildTensorExpFromLinalg(), mlir::failure(), isAdmissibleTensorExp(), op(), and mlir::success().
isAdmissibleTensorExp()
bool CodegenEnv::isAdmissibleTensorExp (ExprId e)
Whether the tensor expression is admissible for codegen.
It also sets the sparseOut if the output tensor is sparse.
Definition at line 154 of file CodegenEnv.cpp.
References exp(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::OpOperand::getOperandNumber(), mlir::sparse_tensor::getSparseTensorType(), mlir::sparse_tensor::Merger::hasNegateOnOut(), mlir::sparse_tensor::SparseTensorType::isAllDense(), isMaterializing(), mlir::sparse_tensor::Merger::isSingleCondition(), and makeTensorId().
Referenced by initTensorExp().
isAdmissibleTopoOrder()
bool CodegenEnv::isAdmissibleTopoOrder ()
Whether the iteration graph is sorted in admissible topoOrder.
Sets outerParNest on success with sparse output
Definition at line 186 of file CodegenEnv.cpp.
References mlir::sparse_tensor::Merger::getNumLoops(), hasSparseOutput(), mlir::sparse_tensor::Merger::isFilterLoop(), mlir::linalg::isReductionIterator(), and topSortSize().
isCustomReduc()
bool mlir::sparse_tensor::CodegenEnv::isCustomReduc () const inline
Definition at line 174 of file CodegenEnv.h.
References mlir::sparse_tensor::detail::kInvalidId.
Referenced by endCustomReduc(), getCustomRedId(), and startCustomReduc().
isExpand()
bool mlir::sparse_tensor::CodegenEnv::isExpand () const inline
Definition at line 152 of file CodegenEnv.h.
Referenced by endIf(), finalizeWhileOp(), genIf(), genLoopBoundary(), and isParallelFor().
isReduc()
bool mlir::sparse_tensor::CodegenEnv::isReduc () const inline
Definition at line 165 of file CodegenEnv.h.
References mlir::sparse_tensor::detail::kInvalidId.
Referenced by clearValidLexInsert(), endIf(), endLoop(), endReduc(), finalizeWhileOp(), genIf(), genLoopBoundary(), setValidLexInsert(), startReduc(), and updateReduc().
isSparseOutput()
bool mlir::sparse_tensor::CodegenEnv::isSparseOutput (OpOperand * o) const inline
Definition at line 144 of file CodegenEnv.h.
lat()
const LatPoint& mlir::sparse_tensor::CodegenEnv::lat (LatPointId l) const inline
Definition at line 79 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::lat().
Referenced by genStmt(), startLoopSeq(), and translateBitsToTidLvlPairs().
makeLoopId()
constexpr LoopId mlir::sparse_tensor::CodegenEnv::makeLoopId (unsigned i) const inline constexpr
Definition at line 72 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::makeLoopId().
Referenced by addSliceBasedConstraints(), genIndex(), and relinkBranch().
makeTensorId()
constexpr TensorId mlir::sparse_tensor::CodegenEnv::makeTensorId (unsigned t) const inline constexpr
Definition at line 69 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::makeTensorId().
Referenced by addFilterLoopBasedConstraints(), computeIterationGraph(), findSparseAnnotations(), genSubscript(), isAdmissibleTensorExp(), and startEmit().
makeTensorLevel()
TensorLevel mlir::sparse_tensor::CodegenEnv::makeTensorLevel (TensorId t, Level l) const inline
Definition at line 92 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::getNumTensors(), mlir::sparse_tensor::LoopEmitter::getNumTensors(), and mlir::sparse_tensor::LoopEmitter::makeTensorLevel().
Referenced by startLoopSeq(), and translateBitsToTidLvlPairs().
makeTensorLoopId()
constexpr TensorLoopId mlir::sparse_tensor::CodegenEnv::makeTensorLoopId (unsigned t, unsigned i) const inline constexpr
Definition at line 75 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::makeTensorLoopId().
merger()
Merger& mlir::sparse_tensor::CodegenEnv::merger () inline
Definition at line 53 of file CodegenEnv.h.
Referenced by addFilterLoopBasedConstraints(), computeIterationGraph(), findSparseAnnotations(), genIf(), genStmt(), permute(), startLoop(), startLoopSeq(), topSortOptimal(), and translateBitsToTidLvlPairs().
op()
linalg::GenericOp mlir::sparse_tensor::CodegenEnv::op () const inline
Definition at line 51 of file CodegenEnv.h.
Referenced by addFilterLoopBasedConstraints(), addSliceBasedConstraints(), computeIterationGraph(), endIf(), endLoop(), endLoopSeq(), finalizeWhileOp(), findSparseAnnotations(), genIf(), genIndex(), genInitConstantDenseAddress(), genSubscript(), genWhile(), getCustomRedId(), initTensorExp(), permute(), startLoop(), and startLoopSeq().
options()
const SparsificationOptions& mlir::sparse_tensor::CodegenEnv::options () const inline
Definition at line 52 of file CodegenEnv.h.
Referenced by isParallelFor().
set()
ArrayRef<LatPointId> mlir::sparse_tensor::CodegenEnv::set (LatSetId s) const inline
Definition at line 80 of file CodegenEnv.h.
References mlir::sparse_tensor::Merger::set().
Referenced by genStmt(), and startLoopSeq().
setValidLexInsert()
void CodegenEnv::setValidLexInsert (Value val)
Definition at line 303 of file CodegenEnv.cpp.
References isReduc().
Referenced by endLoop(), finalizeWhileOp(), and genLoopBoundary().
startCustomReduc()
void CodegenEnv::startCustomReduc (ExprId exp)
Definition at line 313 of file CodegenEnv.cpp.
References exp(), isCustomReduc(), and mlir::sparse_tensor::detail::kInvalidId.
startEmit()
void CodegenEnv::startEmit ()
Definition at line 72 of file CodegenEnv.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::get(), mlir::sparse_tensor::Merger::getDependentLoops(), mlir::sparse_tensor::getSparseTensorEncoding(), mlir::sparse_tensor::LoopEmitter::initialize(), makeTensorId(), mlir::sparse_tensor::Merger::setHasSparseOut(), and sortArrayBasedOnOrder().
startExpand()
void CodegenEnv::startExpand (Value values, Value filled, Value added, Value count)
Definition at line 256 of file CodegenEnv.cpp.
startReduc()
void CodegenEnv::startReduc (ExprId exp, Value val)
Definition at line 279 of file CodegenEnv.cpp.
References exp(), isReduc(), mlir::sparse_tensor::detail::kInvalidId, and updateReduc().
topSortAt()
LoopId mlir::sparse_tensor::CodegenEnv::topSortAt (LoopOrd n) const inline
Definition at line 124 of file CodegenEnv.h.
Referenced by genLoop(), genStmt(), permute(), and startLoop().
topSortClear()
void mlir::sparse_tensor::CodegenEnv::topSortClear (size_t capacity = 0) inline
Definition at line 126 of file CodegenEnv.h.
Referenced by computeIterationGraph().
topSortPushBack()
void mlir::sparse_tensor::CodegenEnv::topSortPushBack (LoopId i) inline
Definition at line 125 of file CodegenEnv.h.
Referenced by topSortOptimal().
topSortSize()
LoopOrd mlir::sparse_tensor::CodegenEnv::topSortSize () const inline
Definition at line 123 of file CodegenEnv.h.
Referenced by genLoop(), genStmt(), getLoopVar(), isAdmissibleTopoOrder(), permute(), and topSortOptimal().
unpackTensorLevel()
std::pair<TensorId, Level> mlir::sparse_tensor::CodegenEnv::unpackTensorLevel (TensorLevel tl) const inline
Definition at line 99 of file CodegenEnv.h.
References mlir::sparse_tensor::LoopEmitter::unpackTensorLevel().
unpackTensorLevelRange()
template<class ContainerTy > auto mlir::sparse_tensor::CodegenEnv::unpackTensorLevelRange (ContainerTy && c) const inline
Definition at line 103 of file CodegenEnv.h.
References mlir::sparse_tensor::LoopEmitter::unpackTensorLevelRange().
Referenced by startLoop().
updateExpandCount()
void CodegenEnv::updateExpandCount (Value count)
Definition at line 265 of file CodegenEnv.cpp.
Referenced by endIf(), finalizeWhileOp(), and genLoopBoundary().
updateInsertionChain()
void CodegenEnv::updateInsertionChain (Value chain)
Definition at line 245 of file CodegenEnv.cpp.
Referenced by endIf(), finalizeWhileOp(), and genLoopBoundary().
updateReduc()
void CodegenEnv::updateReduc (Value val)
Definition at line 285 of file CodegenEnv.cpp.
References isReduc(), and mlir::sparse_tensor::Merger::updateExprValue().
Referenced by endIf(), finalizeWhileOp(), genLoopBoundary(), and startReduc().
The documentation for this class was generated from the following files:
lib/Dialect/SparseTensor/Transforms/CodegenEnv.h
lib/Dialect/SparseTensor/Transforms/CodegenEnv.cpp