MLIR: mlir::transform::TransformResults Class Reference
mlir::transform::TransformResults Class Reference
Local mapping between values defined by a specific op implementing the TransformOpInterface and the payload IR ops they correspond to.
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
Public Member Functions
void set (OpResult value, ArrayRef< Operation * > ops)
Indicates that the result of the transform IR op at the given position corresponds to the given list of payload IR ops.
void setParams (OpResult value, ArrayRef< TransformState::Param > params)
Indicates that the result of the transform IR op at the given position corresponds to the given list of parameters.
void setValues (OpResult handle, ValueRange values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of payload IR values.
void setMappedValues (OpResult handle, ArrayRef< MappedValue > values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of mapped values.
void setRemainingToEmpty (TransformOpInterface transform)
Sets the currently unset results to empty lists of the kind expected by the corresponding results of the given transform op.
Friends
class TransformState
Detailed Description
Local mapping between values defined by a specific op implementing the TransformOpInterface and the payload IR ops they correspond to.
Definition at line 590 of file TransformInterfaces.h.
Member Function Documentation
set()
void transform::TransformResults::set (OpResult value, ArrayRef< Operation * > ops)
Indicates that the result of the transform IR op at the given position corresponds to the given list of payload IR ops.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformHandleTypeInterface.
Definition at line 990 of file TransformInterfaces.cpp.
References mlir::OpResult::getResultNumber().
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply(), applyTilingToAll(), forwardEmptyOperands(), mlir::transform::detail::forwardTerminatorOperands(), and mlir::transform::detail::setApplyToOneResults().
setMappedValues()
void transform::TransformResults::setMappedValues (OpResult handle, ArrayRef< MappedValue > values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of mapped values.
All mapped values are expected to be compatible with the type of the result, e.g., if the result is an operation handle, all mapped values are expected to be payload operations.
Definition at line 1029 of file TransformInterfaces.cpp.
References diag(), dispatchMappedValues(), and mlir::success().
setParams()
void transform::TransformResults::setParams (OpResult value, ArrayRef< TransformState::Param > params)
Indicates that the result of the transform IR op at the given position corresponds to the given list of parameters.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformParamTypeInterface.
Definition at line 1003 of file TransformInterfaces.cpp.
References mlir::OpResult::getResultNumber().
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply(), mlir::transform::detail::forwardTerminatorOperands(), and mlir::transform::detail::setApplyToOneResults().
setRemainingToEmpty()
void transform::TransformResults::setRemainingToEmpty (TransformOpInterface transform)
Sets the currently unset results to empty lists of the kind expected by the corresponding results of the given transform op.
Definition at line 1050 of file TransformInterfaces.cpp.
setValues()
void transform::TransformResults::setValues (OpResult handle, ValueRange values)
Indicates that the result of the transform IR op at the given position corresponds to the given range of payload IR values.
Each result must be set by the transformation exactly once in case of transformation succeeding. The value must have a type implementing TransformValueHandleTypeInterface.
Definition at line 1016 of file TransformInterfaces.cpp.
References mlir::OpResult::getResultNumber().
Referenced by mlir::transform::TransformEachOpTrait< OpTy >::apply(), mlir::transform::detail::forwardTerminatorOperands(), and mlir::transform::detail::setApplyToOneResults().
Friends And Related Function Documentation
TransformState
friend class TransformState friend
Definition at line 591 of file TransformInterfaces.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Transform/IR/TransformInterfaces.h
lib/Dialect/Transform/IR/TransformInterfaces.cpp