MLIR: lib/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.cpp File Reference
ControlFlowToLLVM.cpp File Reference
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/LLVMCommon/VectorPattern.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/LLVMIR/FunctionCallUtils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/StringRef.h"
#include <functional>
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
This header declares functions that assit transformations in the MemRef dialect.
Macros
#define GEN_PASS_DEF_CONVERTCONTROLFLOWTOLLVMPASS
#define PASS_NAME "convert-cf-to-llvm"
Functions
static std::string generateGlobalMsgSymbolName (ModuleOp moduleOp)
static void createPrintMsg (OpBuilder &builder, Location loc, ModuleOp moduleOp, StringRef msg, LLVMTypeConverter &typeConverter)
Generate IR that prints the given string to stderr.
Macro Definition Documentation
GEN_PASS_DEF_CONVERTCONTROLFLOWTOLLVMPASS
#define GEN_PASS_DEF_CONVERTCONTROLFLOWTOLLVMPASS
Definition at line 30 of file ControlFlowToLLVM.cpp.
PASS_NAME
#define PASS_NAME "convert-cf-to-llvm"
Definition at line 36 of file ControlFlowToLLVM.cpp.
Function Documentation
createPrintMsg()
static void createPrintMsg (OpBuilder & builder, Location loc, ModuleOp moduleOp, StringRef msg, LLVMTypeConverter & typeConverter) static
Generate IR that prints the given string to stderr.
Definition at line 47 of file ControlFlowToLLVM.cpp.
References mlir::OpBuilder::create(), generateGlobalMsgSymbolName(), mlir::get(), mlir::DenseElementsAttr::get(), mlir::Builder::getContext(), mlir::Builder::getI8Type(), mlir::LLVMTypeConverter::getPointerType(), mlir::LLVM::lookupOrCreatePrintStrFn(), mlir::OpBuilder::restoreInsertionPoint(), mlir::OpBuilder::saveInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::LLVMTypeConverter::useOpaquePointers().
generateGlobalMsgSymbolName()
static std::string generateGlobalMsgSymbolName (ModuleOp moduleOp) static
Definition at line 38 of file ControlFlowToLLVM.cpp.
Referenced by createPrintMsg().