MLIR: lib/Dialect/Math/Transforms/ExpandPatterns.cpp File Reference
ExpandPatterns.cpp File Reference
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Math/IR/Math.h"
#include "mlir/Dialect/Math/Transforms/Passes.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static Value createFloatConst (Location loc, Type type, double value, OpBuilder &b)
Create a float constant.
static Value createIntConst (Location loc, Type type, int64_t value, OpBuilder &b)
Create a float constant.
static Value createTruncatedFPValue (Value operand, ImplicitLocOpBuilder &b)
static LogicalResult convertTanhOp (math::TanhOp op, PatternRewriter &rewriter)
Expands tanh op into 1) 1-exp^{-2x} / 1+exp^{-2x}, if x => 0 2) exp^{2x}-1 / exp^{2x}+1 , if x < 0.
static LogicalResult convertTanOp (math::TanOp op, PatternRewriter &rewriter)
static LogicalResult convertFmaFOp (math::FmaOp op, PatternRewriter &rewriter)
static LogicalResult convertFloorOp (math::FloorOp op, PatternRewriter &rewriter)
static LogicalResult convertCeilOp (math::CeilOp op, PatternRewriter &rewriter)
static LogicalResult convertPowfOp (math::PowFOp op, PatternRewriter &rewriter)
static LogicalResult convertExp2fOp (math::Exp2Op op, PatternRewriter &rewriter)
static LogicalResult convertRoundOp (math::RoundOp op, PatternRewriter &rewriter)
static LogicalResult convertCtlzOp (math::CountLeadingZerosOp op, PatternRewriter &rewriter)
static LogicalResult convertRoundEvenOp (math::RoundEvenOp op, PatternRewriter &rewriter)
Function Documentation
convertCeilOp()
static LogicalResult convertCeilOp (math::CeilOp op, PatternRewriter & rewriter) static
Definition at line 147 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandCeilFPattern().
convertCtlzOp()
static LogicalResult convertCtlzOp (math::CountLeadingZerosOp op, PatternRewriter & rewriter) static
Definition at line 255 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandCtlzPattern().
convertExp2fOp()
static LogicalResult convertExp2fOp (math::Exp2Op op, PatternRewriter & rewriter) static
Definition at line 183 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandExp2FPattern().
convertFloorOp()
static LogicalResult convertFloorOp (math::FloorOp op, PatternRewriter & rewriter) static
Definition at line 122 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandFloorFPattern().
convertFmaFOp()
static LogicalResult convertFmaFOp (math::FmaOp op, PatternRewriter & rewriter) static
Definition at line 105 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandFmaFPattern().
convertPowfOp()
static LogicalResult convertPowfOp (math::PowFOp op, PatternRewriter & rewriter) static
Definition at line 166 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandPowFPattern().
convertRoundEvenOp()
static LogicalResult convertRoundEvenOp (math::RoundEvenOp op, PatternRewriter & rewriter) static
Definition at line 298 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandRoundEvenPattern().
convertRoundOp()
static LogicalResult convertRoundOp (math::RoundOp op, PatternRewriter & rewriter) static
Definition at line 195 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandRoundFPattern().
convertTanhOp()
static LogicalResult convertTanhOp (math::TanhOp op, PatternRewriter & rewriter) static
Expands tanh op into 1) 1-exp^{-2x} / 1+exp^{-2x}, if x => 0 2) exp^{2x}-1 / exp^{2x}+1 , if x < 0.
Definition at line 64 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandTanhPattern().
convertTanOp()
static LogicalResult convertTanOp (math::TanOp op, PatternRewriter & rewriter) static
Definition at line 94 of file ExpandPatterns.cpp.
Referenced by mlir::populateExpandTanPattern().
createFloatConst()
static Value createFloatConst (Location loc, Type type, double value, OpBuilder & b) static
Create a float constant.
Definition at line 26 of file ExpandPatterns.cpp.
References mlir::OpBuilder::create(), mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), and mlir::Builder::getFloatAttr().
createIntConst()
static Value createIntConst (Location loc, Type type, int64_t value, OpBuilder & b) static
Create a float constant.
Definition at line 38 of file ExpandPatterns.cpp.
References mlir::OpBuilder::create(), mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), and mlir::Builder::getIntegerAttr().
createTruncatedFPValue()
static Value createTruncatedFPValue (Value operand, ImplicitLocOpBuilder & b) static
Definition at line 49 of file ExpandPatterns.cpp.
References mlir::ImplicitLocOpBuilder::create(), mlir::Builder::getI64Type(), and mlir::Value::getType().