MLIR: lib/Conversion/GPUCommon/GPUToLLVMConversion.cpp File Reference
GPUToLLVMConversion.cpp File Reference
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h"
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVMPass.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/Pattern.h"
#include "mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/GPU/IR/GPUDialect.h"
#include "mlir/Dialect/GPU/Transforms/Passes.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FormatVariadic.h"
#include "mlir/Conversion/Passes.h.inc"
Namespaces
mlir
This header declares functions that assit transformations in the MemRef dialect.
Macros
#define GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
Functions
static LogicalResult areAllLLVMTypes (Operation *op, ValueRange operands, ConversionPatternRewriter &rewriter)
static LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter &rewriter, gpu::AsyncOpInterface op)
static bool isGpuAsyncTokenType (Value value)
static bool isDefinedByCallTo (Value value, StringRef functionName)
static Value bitAndAddrspaceCast (Location loc, ConversionPatternRewriter &rewriter, LLVM::LLVMPointerType destinationType, Value sourcePtr, LLVMTypeConverter &typeConverter)
Variables
static constexpr const char * kGpuBinaryStorageSuffix = "_gpubin_cst"
Macro Definition Documentation
GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
#define GEN_PASS_DEF_GPUTOLLVMCONVERSIONPASS
Definition at line 42 of file GPUToLLVMConversion.cpp.
Function Documentation
areAllLLVMTypes()
static LogicalResult areAllLLVMTypes (Operation * op, ValueRange operands, ConversionPatternRewriter & rewriter) static
Definition at line 424 of file GPUToLLVMConversion.cpp.
bitAndAddrspaceCast()
static Value bitAndAddrspaceCast (Location loc, ConversionPatternRewriter & rewriter, LLVM::LLVMPointerType destinationType, Value sourcePtr, LLVMTypeConverter & typeConverter) static
Definition at line 860 of file GPUToLLVMConversion.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::LLVMTypeConverter::getPointerType(), mlir::Value::getType(), and mlir::LLVMTypeConverter::useOpaquePointers().
isAsyncWithOneDependency()
static LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter & rewriter, gpu::AsyncOpInterface op) static
Definition at line 435 of file GPUToLLVMConversion.cpp.
isDefinedByCallTo()
static bool isDefinedByCallTo (Value value, StringRef functionName) static
Definition at line 593 of file GPUToLLVMConversion.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::getType(), and mlir::Type::isa().
isGpuAsyncTokenType()
static bool isGpuAsyncTokenType (Value value) static
Definition at line 557 of file GPUToLLVMConversion.cpp.
References mlir::Value::getType(), and mlir::Type::isa().
Variable Documentation
kGpuBinaryStorageSuffix
constexpr const char* kGpuBinaryStorageSuffix = "_gpubin_cst" static constexpr
Definition at line 48 of file GPUToLLVMConversion.cpp.