MLIR: lib/Dialect/IRDL/IR/IRDL.cpp File Reference
IRDL.cpp File Reference
#include "mlir/Dialect/IRDL/IR/IRDL.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/ExtensibleDialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/Casting.h"
#include "mlir/Dialect/IRDL/IR/IRDL.cpp.inc"
#include "mlir/Dialect/IRDL/IR/IRDLDialect.cpp.inc"
#include "mlir/Dialect/IRDL/IR/IRDLOps.cpp.inc"
#include "mlir/Dialect/IRDL/IR/IRDLTypesGen.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_TYPEDEF_LIST
#define GET_TYPEDEF_CLASSES
#define GET_OP_CLASSES
Functions
static ParseResult parseSingleBlockRegion (OpAsmParser &p, Region &region)
Parse a region, and add a single block if the region is empty.
static void printSingleBlockRegion (OpAsmPrinter &p, Operation *op, Region &region)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 77 of file IRDL.cpp.
GET_OP_LIST
#define GET_OP_LIST
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 74 of file IRDL.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
parseSingleBlockRegion()
static ParseResult parseSingleBlockRegion (OpAsmParser & p, Region & region) static
Parse a region, and add a single block if the region is empty.
If no region is parsed, create a new region with a single empty block.
Definition at line 50 of file IRDL.cpp.
References mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::OpAsmParser::parseOptionalRegion(), mlir::Region::push_back(), and mlir::success().
printSingleBlockRegion()
static void printSingleBlockRegion (OpAsmPrinter & p, Operation * op, Region & region) static
Definition at line 62 of file IRDL.cpp.