MLIR: lib/Dialect/Linalg/TransformOps/LinalgMatchOps.cpp File Reference
LinalgMatchOps.cpp File Reference
#include "mlir/Dialect/Linalg/TransformOps/LinalgMatchOps.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Transform/IR/MatchInterfaces.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/FunctionImplementation.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include "mlir/Dialect/Linalg/TransformOps/LinalgMatchOps.cpp.inc"
Macros
#define DEBUG_TYPE "linalg-transforms"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE "]: ")
#define GET_OP_CLASSES
Functions
static DiagnosedSilenceableFailure containsAll (ArrayRef< unsigned > reference, ArrayRef< int64_t > list, Location loc, const char *message)
Checks if all values from list are also contained in reference.
static DiagnosedSilenceableFailure expandTargetSpecification (Location loc, bool isAll, bool isInverted, ArrayRef< int64_t > rawList, int64_t maxNumber, SmallVectorImpl< int64_t > &result)
Populates result with the positional identifiers relative to maxNumber.
LogicalResult verifyStructuredTransformDimsOp (Operation *op, ArrayRef< int64_t > raw, bool inverted, bool all)
Checks if the positional specification defined is valid and reports errors otherwise.
template<typename OpTy >
LogicalResult verifyStructuredOperandOp (OpTy op)
Verifies a matcher op for structured input or output, specifically the attributes specifying the operand positions.
static ParseResult parseStructuredTransformDims (OpAsmParser &parser, DenseI64ArrayAttr &rawDimList, UnitAttr &isInverted, UnitAttr &isAll)
Parses a positional specification for structured transform operations.
static void printStructuredTransformDims (OpAsmPrinter &printer, Operation *op, DenseI64ArrayAttr rawDimList, UnitAttr isInverted, UnitAttr isAll)
Prints a positional specification for structured transform operations.
static ParseResult parseSemiFunctionType (OpAsmParser &parser, Type &argumentType, Type &resultType)
Parses a single non-function type or a function type with at least one argument.
static ParseResult parseSemiFunctionType (OpAsmParser &parser, Type &argumentType, SmallVectorImpl< Type > &resultTypes)
static void printSemiFunctionType (OpAsmPrinter &printer, Operation *op, Type argumentType, TypeRange resultType)
Prints argument and result types in a syntax similar to that of FunctionType but allowing and requiring one to omit the parens around the argument type in absence of result types, and without the trailing -> ().
static void printSemiFunctionType (OpAsmPrinter &printer, Operation *op, Type argumentType, Type resultType)
Variables
constexpr static const llvm::StringLiteral kDimExceptKeyword = "except"
Keyword syntax for positional specification inversion.
constexpr static const llvm::StringLiteral kDimAllKeyword = "all"
Keyword syntax for full inclusion in positional specification.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE "]: ")
Definition at line 21 of file LinalgMatchOps.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 20 of file LinalgMatchOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 825 of file LinalgMatchOps.cpp.
Function Documentation
containsAll()
static DiagnosedSilenceableFailure containsAll (ArrayRef< unsigned > reference, ArrayRef< int64_t > list, Location loc, const char * message) static
Checks if all values from list are also contained in reference.
Returns a silenceable error with the given message at the given location when it is not the case. The error message must contain the "{0}" placeholder that will be substituted with the value from list that is not contained in reference.
Definition at line 208 of file LinalgMatchOps.cpp.
References mlir::emitSilenceableFailure(), and mlir::DiagnosedSilenceableFailure::success().
expandTargetSpecification()
static DiagnosedSilenceableFailure expandTargetSpecification (Location loc, bool isAll, bool isInverted, ArrayRef< int64_t > rawList, int64_t maxNumber, SmallVectorImpl< int64_t > & result) static
Populates result with the positional identifiers relative to maxNumber.
If isAll is set, the result will contain all numbers from 0 to maxNumber - 1 inclusive regardless of rawList. Otherwise, negative values from rawList are are interpreted as counting backwards from maxNumber, i.e., -1 is interpreted a maxNumber - 1, while positive numbers remain as is. If isInverted is set, populates result with those values from the 0 to maxNumber - 1 inclusive range that don't appear in rawList. If rawList contains values that are greater than or equal to maxNumber or less than -maxNumber, produces a silenceable error at the given location. maxNumber must be positive. If rawList contains duplicate numbers or numbers that become duplicate after negative value remapping, emits a silenceable error.
Definition at line 236 of file LinalgMatchOps.cpp.
References mlir::emitSilenceableFailure(), and mlir::DiagnosedSilenceableFailure::success().
parseSemiFunctionType() [1/2]
static ParseResult parseSemiFunctionType (OpAsmParser & parser, Type & argumentType, SmallVectorImpl< Type > & resultTypes) static
Definition at line 772 of file LinalgMatchOps.cpp.
References mlir::LogicalResult::failed(), mlir::failure(), mlir::AsmParser::parseArrow(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::AsmParser::parseTypeList(), mlir::LogicalResult::succeeded(), and mlir::success().
parseSemiFunctionType() [2/2]
static ParseResult parseSemiFunctionType (OpAsmParser & parser, Type & argumentType, Type & resultType) static
Parses a single non-function type or a function type with at least one argument.
This allows for the following syntax:
type: just the argument type;
(type) -> type: one argument and one result type;
(type) -> (comma-separated-type-list): one argument and multiple result types.
Unlike FunctionType, this allows and requires one to omit the parens around the argument type in absence of result types, and does not accept the trailing -> () construct, which makes the syntax nicer for operations.
Definition at line 759 of file LinalgMatchOps.cpp.
References mlir::LogicalResult::failed(), mlir::failure(), mlir::AsmParser::parseArrow(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::LogicalResult::succeeded(), and mlir::success().
parseStructuredTransformDims()
static ParseResult parseStructuredTransformDims (OpAsmParser & parser, DenseI64ArrayAttr & rawDimList, UnitAttr & isInverted, UnitAttr & isAll) static
Parses a positional specification for structured transform operations.
The following forms are accepted:
all: sets isAll and returns;
comma-separated-integer-list: populates rawDimList with the values;
except (comma-separated-integer-list): populates rawDimList with the values and sets isInverted.
Definition at line 693 of file LinalgMatchOps.cpp.
References mlir::LogicalResult::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getDenseI64ArrayAttr(), mlir::Builder::getUnitAttr(), kDimAllKeyword, kDimExceptKeyword, mlir::AsmParser::parseCommaSeparatedList(), mlir::AsmParser::parseInteger(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), mlir::LogicalResult::succeeded(), and mlir::success().
printSemiFunctionType() [1/2]
static void printSemiFunctionType (OpAsmPrinter & printer, Operation * op, Type argumentType, Type resultType) static
Definition at line 818 of file LinalgMatchOps.cpp.
printSemiFunctionType() [2/2]
static void printSemiFunctionType (OpAsmPrinter & printer, Operation * op, Type argumentType, TypeRange resultType) static
Prints argument and result types in a syntax similar to that of FunctionType but allowing and requiring one to omit the parens around the argument type in absence of result types, and without the trailing -> ().
Definition at line 803 of file LinalgMatchOps.cpp.
printStructuredTransformDims()
static void printStructuredTransformDims (OpAsmPrinter & printer, Operation * op, DenseI64ArrayAttr rawDimList, UnitAttr isInverted, UnitAttr isAll) static
Prints a positional specification for structured transform operations.
Definition at line 732 of file LinalgMatchOps.cpp.
verifyStructuredOperandOp()
template<typename OpTy > LogicalResult verifyStructuredOperandOp (OpTy op)
Verifies a matcher op for structured input or output, specifically the attributes specifying the operand positions.
Definition at line 463 of file LinalgMatchOps.cpp.
verifyStructuredTransformDimsOp()
LogicalResult verifyStructuredTransformDimsOp (Operation * op, ArrayRef< int64_t > raw, bool inverted, bool all)
Checks if the positional specification defined is valid and reports errors otherwise.
Definition at line 283 of file LinalgMatchOps.cpp.
Variable Documentation
kDimAllKeyword
constexpr static const llvm::StringLiteral kDimAllKeyword = "all" static constexpr
Keyword syntax for full inclusion in positional specification.
Definition at line 684 of file LinalgMatchOps.cpp.
Referenced by parseStructuredTransformDims().
kDimExceptKeyword
constexpr static const llvm::StringLiteral kDimExceptKeyword = "except" static constexpr
Keyword syntax for positional specification inversion.
Definition at line 681 of file LinalgMatchOps.cpp.
Referenced by parseStructuredTransformDims().