MLIR: lib/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.cpp File Reference
LLVMToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/MatrixBuilder.h"
#include "llvm/IR/Operator.h"
#include "mlir/Dialect/LLVMIR/LLVMConversionEnumsToLLVM.inc"
#include "mlir/Dialect/LLVMIR/LLVMConversions.inc"
#include "mlir/Dialect/LLVMIR/LLVMIntrinsicConversions.inc"
Functions
static llvm::FastMathFlags getFastmathFlags (FastmathFlagsInterface &op)
static SmallVector< unsigned > extractPosition (ArrayRef< int64_t > indices)
Convert the value of a DenseI64ArrayAttr to a vector of unsigned indices.
static FailureOr< llvm::Function * > getOverloadedDeclaration (CallIntrinsicOp &op, llvm::Intrinsic::ID id, llvm::Module *module, LLVM::ModuleTranslation &moduleTranslation)
Get the declaration of an overloaded llvm intrinsic.
static LogicalResult convertCallLLVMIntrinsicOp (CallIntrinsicOp &op, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Builder for LLVM_CallIntrinsicOp.
static llvm::MDNode * convertBranchWeights (std::optional< ElementsAttr > weights, LLVM::ModuleTranslation &moduleTranslation)
Constructs branch weights metadata if the provided weights hold a value, otherwise returns nullptr.
static LogicalResult convertOperationImpl (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Function Documentation
convertBranchWeights()
static llvm::MDNode* convertBranchWeights (std::optional< ElementsAttr > weights, LLVM::ModuleTranslation & moduleTranslation) static
Constructs branch weights metadata if the provided weights hold a value, otherwise returns nullptr.
Definition at line 127 of file LLVMToLLVMIRTranslation.cpp.
References mlir::LLVM::ModuleTranslation::getLLVMContext().
Referenced by convertOperationImpl().
convertCallLLVMIntrinsicOp()
static LogicalResult convertCallLLVMIntrinsicOp (CallIntrinsicOp & op, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Builder for LLVM_CallIntrinsicOp.
Definition at line 97 of file LLVMToLLVMIRTranslation.cpp.
convertOperationImpl()
static LogicalResult convertOperationImpl (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 140 of file LLVMToLLVMIRTranslation.cpp.
References mlir::Attribute::cast(), convertBranchWeights(), mlir::LLVM::ModuleTranslation::convertType(), mlir::detail::enumerate(), mlir::failure(), mlir::get(), mlir::Operation::getAttrOfType(), mlir::Operation::getContext(), mlir::LLVM::ModuleTranslation::getContext(), getFastmathFlags(), mlir::LLVM::ModuleTranslation::getLLVMContext(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::LLVM::ModuleTranslation::lookupBlock(), mlir::LLVM::ModuleTranslation::lookupFunction(), mlir::LLVM::ModuleTranslation::lookupGlobal(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::lookupValues(), mlir::LLVM::ModuleTranslation::mapBranch(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::LLVM::ModuleTranslation::setLoopMetadata(), mlir::success(), and mlir::LLVM::ModuleTranslation::symbolTable().
extractPosition()
static SmallVector<unsigned> extractPosition (ArrayRef< int64_t > indices) static
Convert the value of a DenseI64ArrayAttr to a vector of unsigned indices.
Definition at line 54 of file LLVMToLLVMIRTranslation.cpp.
getFastmathFlags()
static llvm::FastMathFlags getFastmathFlags (FastmathFlagsInterface & op) static
Definition at line 31 of file LLVMToLLVMIRTranslation.cpp.
Referenced by convertOperationImpl().
getOverloadedDeclaration()
static FailureOr<llvm::Function *> getOverloadedDeclaration (CallIntrinsicOp & op, llvm::Intrinsic::ID id, llvm::Module * module, LLVM::ModuleTranslation & moduleTranslation) static
Get the declaration of an overloaded llvm intrinsic.
First we get the overloaded argument types and/or result type from the CallIntrinsicOp, and then use those to get the correct declaration of the overloaded intrinsic.
Definition at line 64 of file LLVMToLLVMIRTranslation.cpp.