MLIR: lib/Dialect/LLVMIR/IR/LLVMInlining.cpp File Reference
LLVMInlining.cpp File Reference
#include "LLVMInlining.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Interfaces/DataLayoutInterfaces.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "llvm-inliner"
Functions
static bool hasLifetimeMarkers (LLVM::AllocaOp allocaOp)
Check whether the given alloca is an input to a lifetime intrinsic, optionally passing through one or more casts on the way.
static void handleInlinedAllocas (Operation *call, iterator_range< Region::iterator > inlinedBlocks)
Handles alloca operations in the inlined blocks:
static unsigned tryToEnforceAllocaAlignment (LLVM::AllocaOp alloca, unsigned requestedAlignment, DataLayout const &dataLayout)
If requestedAlignment is higher than the alignment specified on alloca, realigns alloca if this does not exceed the natural stack alignment.
static unsigned tryToEnforceAlignment (Value value, unsigned requestedAlignment, DataLayout const &dataLayout)
Tries to find and return the alignment of the pointer value by looking for an alignment attribute on the defining allocation op or function argument.
static Value handleByValArgumentInit (OpBuilder &builder, Location loc, Value argument, Type elementType, unsigned elementTypeSize, unsigned targetAlignment)
Introduces a new alloca and copies the memory pointed to by argument to the address of the new alloca, then returns the value of the new alloca.
static Value handleByValArgument (OpBuilder &builder, Operation *callable, Value argument, Type elementType, unsigned requestedAlignment)
Handles a function argument marked with the byval attribute by introducing a memcpy or realigning the defining operation, if required either due to the pointee being writeable in the callee, and/or due to an alignment mismatch.
static bool isArgOrResAttrSupported (NamedAttribute attr)
Returns true if the given argument or result attribute is supported by the inliner, false otherwise.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "llvm-inliner"
Definition at line 21 of file LLVMInlining.cpp.
Function Documentation
handleByValArgument()
static Value handleByValArgument (OpBuilder & builder, Operation * callable, Value argument, Type elementType, unsigned requestedAlignment) static
Handles a function argument marked with the byval attribute by introducing a memcpy or realigning the defining operation, if required either due to the pointee being writeable in the callee, and/or due to an alignment mismatch.
requestedAlignment specifies the alignment set in the "align" argument attribute (or 1 if no align attribute was set).
Definition at line 221 of file LLVMInlining.cpp.
References mlir::DataLayout::closest(), mlir::DataLayout::getTypeABIAlignment(), mlir::DataLayout::getTypeSize(), handleByValArgumentInit(), max(), and tryToEnforceAlignment().
handleByValArgumentInit()
static Value handleByValArgumentInit (OpBuilder & builder, Location loc, Value argument, Type elementType, unsigned elementTypeSize, unsigned targetAlignment) static
Introduces a new alloca and copies the memory pointed to by argument to the address of the new alloca, then returns the value of the new alloca.
Definition at line 190 of file LLVMInlining.cpp.
References mlir::Region::begin(), mlir::OpBuilder::create(), mlir::Builder::getBoolAttr(), mlir::Builder::getI1Type(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getI64Type(), mlir::Value::getParentRegion(), mlir::Value::getType(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by handleByValArgument().
handleInlinedAllocas()
static void handleInlinedAllocas (Operation * call, iterator_range< Region::iterator > inlinedBlocks) static
Handles alloca operations in the inlined blocks:
Moves all alloca operations with a constant size in the former entry block of the callee into the entry block of the caller, so they become part of the function prologue/epilogue during code generation.
Inserts lifetime intrinsics that limit the scope of inlined static allocas to the inlined blocks.
Inserts StackSave and StackRestore operations if dynamic allocas were inlined.
Definition at line 50 of file LLVMInlining.cpp.
References mlir::Block::begin(), mlir::Region::begin(), mlir::OpBuilder::create(), mlir::get(), mlir::Operation::getContext(), mlir::Operation::getLoc(), mlir::Block::getOps(), mlir::Block::getParent(), hasLifetimeMarkers(), mlir::m_Constant(), mlir::matchPattern(), mlir::Operation::moveAfter(), and mlir::OpBuilder::setInsertionPoint().
hasLifetimeMarkers()
static bool hasLifetimeMarkers (LLVM::AllocaOp allocaOp) static
Check whether the given alloca is an input to a lifetime intrinsic, optionally passing through one or more casts on the way.
This is not transitive through block arguments.
Definition at line 28 of file LLVMInlining.cpp.
Referenced by handleInlinedAllocas().
isArgOrResAttrSupported()
static bool isArgOrResAttrSupported (NamedAttribute attr) static
Returns true if the given argument or result attribute is supported by the inliner, false otherwise.
Definition at line 250 of file LLVMInlining.cpp.
References mlir::NamedAttribute::getName().
tryToEnforceAlignment()
static unsigned tryToEnforceAlignment (Value value, unsigned requestedAlignment, DataLayout const & dataLayout) static
Tries to find and return the alignment of the pointer value by looking for an alignment attribute on the defining allocation op or function argument.
If the found alignment is lower than requestedAlignment, tries to realign the pointer, then returns the resulting post-alignment, regardless of whether it was realigned or not. If no existing alignment attribute is found, returns 1 (i.e., assume that no alignment is guaranteed).
Definition at line 160 of file LLVMInlining.cpp.
References mlir::Value::cast(), mlir::Value::getDefiningOp(), mlir::Value::getParentBlock(), mlir::Block::getParentOp(), and tryToEnforceAllocaAlignment().
Referenced by handleByValArgument().
tryToEnforceAllocaAlignment()
static unsigned tryToEnforceAllocaAlignment (LLVM::AllocaOp alloca, unsigned requestedAlignment, DataLayout const & dataLayout) static
If requestedAlignment is higher than the alignment specified on alloca, realigns alloca if this does not exceed the natural stack alignment.
Returns the post-alignment of alloca, whether it was realigned or not.
Definition at line 131 of file LLVMInlining.cpp.
References mlir::DataLayout::getStackAlignment().
Referenced by tryToEnforceAlignment().