MLIR: lib/CAPI/Dialect/LLVM.cpp File Reference
LLVM.cpp File Reference
#include "mlir-c/Dialect/LLVM.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Functions
MlirType mlirLLVMPointerTypeGet (MlirType pointee, unsigned addressSpace)
Creates an llvm.ptr type.
MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const *argumentTypes, bool isVarArg)
Creates an llvm.func type.
MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const *fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
Function Documentation
mlirLLVMArrayTypeGet()
MlirType mlirLLVMArrayTypeGet (MlirType elementType, unsigned numElements)
Creates an llvm.array type.
Definition at line 27 of file LLVM.cpp.
References mlir::get(), unwrap(), and wrap().
mlirLLVMFunctionTypeGet()
MlirType mlirLLVMFunctionTypeGet (MlirType resultType, intptr_t nArgumentTypes, MlirType const * argumentTypes, bool isVarArg)
Creates an llvm.func type.
Definition at line 31 of file LLVM.cpp.
References mlir::get(), unwrap(), unwrapList(), and wrap().
mlirLLVMPointerTypeGet()
MlirType mlirLLVMPointerTypeGet (MlirType pointee, unsigned addressSpace)
Creates an llvm.ptr type.
Definition at line 19 of file LLVM.cpp.
References mlir::get(), unwrap(), and wrap().
mlirLLVMStructTypeLiteralGet()
MlirType mlirLLVMStructTypeLiteralGet (MlirContext ctx, intptr_t nFieldTypes, MlirType const * fieldTypes, bool isPacked)
Creates an LLVM literal (unnamed) struct type.
Definition at line 39 of file LLVM.cpp.
References mlir::LLVM::LLVMStructType::getLiteral(), unwrap(), unwrapList(), and wrap().
mlirLLVMVoidTypeGet()
MlirType mlirLLVMVoidTypeGet (MlirContext ctx)
Creates an llmv.void type.
Definition at line 23 of file LLVM.cpp.
References mlir::get(), unwrap(), and wrap().