MLIR: lib/Tools/mlir-opt/MlirOptMain.cpp File Reference
MlirOptMain.cpp File Reference
#include "mlir/Tools/mlir-opt/MlirOptMain.h"
#include "mlir/Bytecode/BytecodeWriter.h"
#include "mlir/Debug/CLOptionsSetup.h"
#include "mlir/Debug/Counter.h"
#include "mlir/Debug/DebuggerExecutionContextHook.h"
#include "mlir/Debug/ExecutionContext.h"
#include "mlir/Debug/Observers/ActionLogging.h"
#include "mlir/Dialect/IRDL/IR/IRDL.h"
#include "mlir/Dialect/IRDL/IRDLLoading.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Support/Timing.h"
#include "mlir/Support/ToolUtilities.h"
#include "mlir/Tools/ParseUtilities.h"
#include "mlir/Tools/Plugins/DialectPlugin.h"
#include "mlir/Tools/Plugins/PassPlugin.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/ThreadPool.h"
#include "llvm/Support/ToolOutputFile.h"
Functions
static LogicalResult performActions (raw_ostream &os, const std::shared_ptr< llvm::SourceMgr > &sourceMgr, MLIRContext *context, const MlirOptMainConfig &config)
Perform the actions on the input file indicated by the command line flags within the specified context.
LogicalResult loadIRDLDialects (StringRef irdlFile, MLIRContext &ctx)
static LogicalResult processBuffer (raw_ostream &os, std::unique_ptr< MemoryBuffer > ownedBuffer, const MlirOptMainConfig &config, DialectRegistry &registry, llvm::ThreadPool *threadPool)
Parses the memory buffer.
Variables
ManagedStatic< MlirOptMainConfigCLOptions > clOptionsConfig
Function Documentation
loadIRDLDialects()
LogicalResult loadIRDLDialects (StringRef irdlFile, MLIRContext & ctx)
Definition at line 289 of file MlirOptMain.cpp.
References mlir::MLIRContext::appendDialectRegistry(), mlir::emitError(), mlir::failure(), mlir::OwningOpRef< OpTy >::get(), mlir::get(), mlir::DialectRegistry::insert(), mlir::irdl::loadDialects(), and mlir::openInputFile().
Referenced by processBuffer().
performActions()
static LogicalResult performActions (raw_ostream & os, const std::shared_ptr< llvm::SourceMgr > & sourceMgr, MLIRContext * context, const MlirOptMainConfig & config) static
Perform the actions on the input file indicated by the command line flags within the specified context.
This typically parses the main source file, runs zero or more optimization passes, then prints the output.
Definition at line 223 of file MlirOptMain.cpp.
References mlir::applyDefaultTimingManagerCLOptions(), mlir::PassReproducerOptions::attachResourceParser(), mlir::MLIRContext::disableMultithreading(), mlir::TimingManager::getRootScope(), mlir::MLIRContext::isMultithreadingEnabled(), mlir::TimingScope::nest(), and mlir::MlirOptMainConfig::shouldRunReproducer().
Referenced by processBuffer().
processBuffer()
static LogicalResult processBuffer (raw_ostream & os, std::unique_ptr< MemoryBuffer > ownedBuffer, const MlirOptMainConfig & config, DialectRegistry & registry, llvm::ThreadPool * threadPool) static
Parses the memory buffer.
If successfully, run a series of passes against it and print the result.
Definition at line 318 of file MlirOptMain.cpp.
References mlir::MLIRContext::allowUnregisteredDialects(), mlir::MLIRContext::DISABLED, mlir::failed(), mlir::failure(), mlir::MlirOptMainConfig::getDebugConfig(), mlir::MlirOptMainConfig::getIrdlFile(), loadIRDLDialects(), performActions(), mlir::MLIRContext::printOpOnDiagnostic(), mlir::MLIRContext::setThreadPool(), mlir::MlirOptMainConfig::shouldAllowUnregisteredDialects(), mlir::MlirOptMainConfig::shouldVerifyDiagnostics(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().
Referenced by mlir::MlirOptMain().
Variable Documentation
clOptionsConfig
ManagedStatic<MlirOptMainConfigCLOptions> clOptionsConfig
Definition at line 172 of file MlirOptMain.cpp.
Referenced by mlir::MlirOptMainConfig::createFromCLOptions(), and mlir::MlirOptMainConfig::registerCLOptions().