MLIR: mlir::transform Namespace Reference
mlir::transform Namespace Reference
Namespaces
detail
gpu
Classes
class StructuredOpPredicateOpTrait
struct TileSizesSpec
struct NumThreadsSpec
class SingleOpMatcherOpTrait
class SingleValueMatcherOpTrait
class TransformDialectExtension
Base class for extensions of the Transform dialect that supports injecting operations into the Transform dialect at load time.
class BuildOnly
A wrapper for transform dialect extensions that forces them to be constructed in the build-only mode.
class TransformOptions
Options controlling the application of transform operations by the TransformState.
class TransformState
The state maintained across applications of various ops implementing the TransformOpInterface.
class TransformResults
Local mapping between values defined by a specific op implementing the TransformOpInterface and the payload IR ops they correspond to.
class PossibleTopLevelTransformOpTrait
This trait is supposed to be attached to Transform dialect operations that can be standalone top-level transforms.
class TransformEachOpTrait
Trait implementing the TransformOpInterface for operations applying a transformation to a single operation handle and producing an arbitrary number of handles and parameter values.
class TransformWithPatternsOpTrait
Trait implementing the applyToOne function required by TransformEachOpTrait by greedily applying a set of patterns to each target payload operation.
struct TransformMappingResource
Side effect resource corresponding to the mapping between Transform IR values and Payload IR operations.
struct PayloadIRResource
Side effect resource corresponding to the Payload IR itself.
class FunctionalStyleTransformOpTrait
Trait implementing the MemoryEffectOpInterface for operations that "consume" their operands and produce new results.
class NavigationTransformOpTrait
Trait implementing the MemoryEffectOpInterface for single-operand single-result operations that use their operand without consuming and without modifying the Payload IR to produce a new handle.
class ParamProducerTransformOpTrait
Trait implementing the MemoryEffectsOpInterface for operations that produce transform dialect parameters.
class ApplyToEachResultList
A list of results of applying a transform op with ApplyEachOpTrait to a single payload operation, co-indexed with the results of the transform op.
class TrackingListener
A listener that updates a TransformState based on IR modifications.
class TransformInterpreterPassBase
Base class for transform dialect interpreter passes that can consume and dump transform dialect scripts in separate files.
Typedefs
using Param = Attribute
using MappedValue = llvm::PointerUnion< Operation *, Param, Value >
using ApplyToEachResult = MappedValue
A single result of applying a transform op with ApplyEachOpTrait to a single payload operation.
using SequenceBodyBuilderFn = ::llvm::function_ref< void(::mlir::OpBuilder &, ::mlir::Location, ::mlir::BlockArgument)>
A builder function that populates the body of a SequenceOp.
using SequenceBodyBuilderArgsFn = ::llvm::function_ref< void(::mlir::OpBuilder &, ::mlir::Location, ::mlir::BlockArgument, ::mlir::ValueRange)>
Functions
DiagnosedSilenceableFailure tileToForallOpImpl (RewriterBase &rewriter, transform::TransformState &state, TransformOpInterface transformOp, ArrayRef< Operation * > targets, ArrayRef< OpFoldResult > mixedNumThreads, ArrayRef< OpFoldResult > mixedTileSizes, std::optional< ArrayAttr > mapping, SmallVector< Operation * > &tileOps, SmallVector< Operation * > &tiledOps)
Implementation of tiling operations using scf.forall.
LogicalResult applyTransforms (Operation *payloadRoot, TransformOpInterface transform, const RaggedArray< MappedValue > &extraMapping={}, const TransformOptions &options=TransformOptions())
Entry point to the Transform dialect infrastructure.
void consumesHandle (ValueRange handles, SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
Populates effects with the memory effects indicating the operation on the given handle value:
void producesHandle (ValueRange handles, SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
void onlyReadsHandle (ValueRange handles, SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
bool isHandleConsumed (Value handle, transform::TransformOpInterface transform)
Checks whether the transform op consumes the given handle.
void modifiesPayload (SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
Populates effects with the memory effects indicating the access to payload IR resource.
void onlyReadsPayload (SmallVectorImpl< MemoryEffects::EffectInstance > &effects)
void getConsumedBlockArguments (Block &block, llvm::SmallDenseSet< unsigned > &consumedArguments)
Populates consumedArguments with positions of block arguments that are consumed by the operations in the block.
void printPackedOrDynamicIndexList (OpAsmPrinter &printer, Operation *op, Value packed, OperandRange values, ArrayRef< int64_t > integers)
Printer hook for custom directive in assemblyFormat.
ParseResult parsePackedOrDynamicIndexList (OpAsmParser &parser, std::optional< OpAsmParser::UnresolvedOperand > &packed, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &values, DenseI64ArrayAttr &integers)
Pasrer hook for custom directive in assemblyFormat.
Typedef Documentation
ApplyToEachResult
using mlir::transform::ApplyToEachResult = typedef MappedValue
A single result of applying a transform op with ApplyEachOpTrait to a single payload operation.
Definition at line 981 of file TransformInterfaces.h.
MappedValue
using mlir::transform::MappedValue = typedef llvm::PointerUnion<Operation *, Param, Value>
Definition at line 50 of file TransformInterfaces.h.
Param
using mlir::transform::Param = typedef Attribute
Definition at line 49 of file TransformInterfaces.h.
SequenceBodyBuilderArgsFn
using mlir::transform::SequenceBodyBuilderArgsFn = typedef ::llvm::function_ref<void(::mlir::OpBuilder &, ::mlir::Location, ::mlir::BlockArgument, ::mlir::ValueRange)>
Definition at line 34 of file TransformOps.h.
SequenceBodyBuilderFn
using mlir::transform::SequenceBodyBuilderFn = typedef ::llvm::function_ref<void(::mlir::OpBuilder &, ::mlir::Location, ::mlir::BlockArgument)>
A builder function that populates the body of a SequenceOp.
Definition at line 32 of file TransformOps.h.
Function Documentation
applyTransforms()
LogicalResult mlir::transform::applyTransforms (Operation * payloadRoot, TransformOpInterface transform, const RaggedArray< MappedValue > & extraMapping = {}, const TransformOptions & options = TransformOptions())
Entry point to the Transform dialect infrastructure.
Applies the transformation specified by transform to payload IR contained in payloadRoot. The transform operation may contain other operations that will be executed following the internal logic of the operation. It must have the PossibleTopLevelTransformOp trait and not have any operands. This function internally keeps track of the transformation state.
Definition at line 1554 of file TransformInterfaces.cpp.
References mlir::transform::TransformState::applyTransform(), mlir::DiagnosedSilenceableFailure::checkAndReport(), and options.
Referenced by mlir::transform::detail::interpreterBaseRunOnOperationImpl().
consumesHandle()
void mlir::transform::consumesHandle (ValueRange handles, SmallVectorImpl< MemoryEffects::EffectInstance > & effects)
Populates effects with the memory effects indicating the operation on the given handle value:
consumes = Read + Free,
produces = Allocate + Write,
onlyReads = Read.
Definition at line 1398 of file TransformInterfaces.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), and mlir::SideEffects::Resource::Base< TransformMappingResource >::get().
Referenced by mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::getEffects().
getConsumedBlockArguments()
void mlir::transform::getConsumedBlockArguments (Block & block, llvm::SmallDenseSet< unsigned > & consumedArguments)
Populates consumedArguments with positions of block arguments that are consumed by the operations in the block.
isHandleConsumed()
bool mlir::transform::isHandleConsumed (Value handle, transform::TransformOpInterface transform)
Checks whether the transform op consumes the given handle.
Definition at line 1419 of file TransformInterfaces.cpp.
Referenced by mlir::transform::TransformState::applyTransform(), and isValueUsePotentialConsumer().
modifiesPayload()
void mlir::transform::modifiesPayload (SmallVectorImpl< MemoryEffects::EffectInstance > & effects)
Populates effects with the memory effects indicating the access to payload IR resource.
Definition at line 1448 of file TransformInterfaces.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), and mlir::SideEffects::Resource::Base< PayloadIRResource >::get().
Referenced by mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::getEffects().
onlyReadsHandle()
void mlir::transform::onlyReadsHandle (ValueRange handles, SmallVectorImpl< MemoryEffects::EffectInstance > & effects)
Definition at line 1439 of file TransformInterfaces.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), and mlir::SideEffects::Resource::Base< TransformMappingResource >::get().
Referenced by mlir::transform::SingleOpMatcherOpTrait< OpTy >::getEffects(), mlir::transform::SingleValueMatcherOpTrait< OpTy >::getEffects(), mlir::transform::NavigationTransformOpTrait< OpTy >::getEffects(), and getPotentialTopLevelEffects().
onlyReadsPayload()
void mlir::transform::onlyReadsPayload (SmallVectorImpl< MemoryEffects::EffectInstance > & effects)
Definition at line 1454 of file TransformInterfaces.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), and mlir::SideEffects::Resource::Base< PayloadIRResource >::get().
Referenced by mlir::transform::SingleOpMatcherOpTrait< OpTy >::getEffects(), mlir::transform::SingleValueMatcherOpTrait< OpTy >::getEffects(), and mlir::transform::NavigationTransformOpTrait< OpTy >::getEffects().
parsePackedOrDynamicIndexList()
ParseResult mlir::transform::parsePackedOrDynamicIndexList (OpAsmParser & parser, std::optional< OpAsmParser::UnresolvedOperand > & packed, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & values, DenseI64ArrayAttr & integers)
Pasrer hook for custom directive in assemblyFormat.
custom<PackedOrDynamicIndexList>($packed, $values, $integers)
See printPackedOrDynamicIndexList for details.
Definition at line 28 of file Utils.cpp.
References mlir::AsmParser::getBuilder(), mlir::Builder::getDenseI64ArrayAttr(), mlir::OptionalParseResult::has_value(), mlir::parseDynamicIndexList(), mlir::OpAsmParser::parseOptionalOperand(), and mlir::success().
printPackedOrDynamicIndexList()
void mlir::transform::printPackedOrDynamicIndexList (OpAsmPrinter & printer, Operation * op, Value packed, OperandRange values, ArrayRef< int64_t > integers)
Printer hook for custom directive in assemblyFormat.
custom<PackedOrDynamicIndexList>($packed, $values, $integers)
where values are variadic Index values, integers is an I64ArrayAttr and packed is a single transform dialect handle who's mapped payload ops have a single Index result and represent the index list. Either packed or the other two parameters may be specified.
This allows idiomatic printing of mixed value and integer attributes in a list or with a single handle. E.g., [arg0, 7, 42, arg42] or just h.
Definition at line 17 of file Utils.cpp.
producesHandle()
void mlir::transform::producesHandle (ValueRange handles, SmallVectorImpl< MemoryEffects::EffectInstance > & effects)
Definition at line 1428 of file TransformInterfaces.cpp.
References mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), and mlir::SideEffects::Resource::Base< TransformMappingResource >::get().
Referenced by mlir::transform::SingleOpMatcherOpTrait< OpTy >::getEffects(), mlir::transform::SingleValueMatcherOpTrait< OpTy >::getEffects(), mlir::transform::FunctionalStyleTransformOpTrait< OpTy >::getEffects(), mlir::transform::NavigationTransformOpTrait< OpTy >::getEffects(), and getPotentialTopLevelEffects().
tileToForallOpImpl()
DiagnosedSilenceableFailure mlir::transform::tileToForallOpImpl (RewriterBase & rewriter, transform::TransformState & state, TransformOpInterface transformOp, ArrayRef< Operation * > targets, ArrayRef< OpFoldResult > mixedNumThreads, ArrayRef< OpFoldResult > mixedTileSizes, std::optional< ArrayAttr > mapping, SmallVector< Operation * > & tileOps, SmallVector< Operation * > & tiledOps)
Implementation of tiling operations using scf.forall.
Definition at line 2507 of file LinalgTransformOps.cpp.
References diag(), mlir::failed(), mlir::failure(), mlir::Value::getLoc(), mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::DiagnosedSilenceableFailure::success(), mlir::linalg::tileToForallOp(), and mlir::linalg::tileToForallOpUsingTileSizes().