MLIR: mlir::bufferization::detail Namespace Reference
mlir::bufferization::detail Namespace Reference
Functions
AliasingOpOperandList defaultGetAliasingOpOperands (OpResult opResult, const AnalysisState &state)
This is the default implementation of BufferizableOpInterface::getAliasingOpOperands.
FailureOr< BaseMemRefType > defaultGetBufferType (Value value, const BufferizationOptions &options, const DenseMap< Value, BaseMemRefType > &fixedTypes)
This is the default implementation of BufferizableOpInterface::getBufferType.
bool defaultResultBufferizesToMemoryWrite (OpResult opResult, const AnalysisState &state)
This is the default implementation of BufferizableOpInterface::resultBufferizesToMemoryWrite.
bool defaultIsRepetitiveRegion (BufferizableOpInterface bufferizableOp, unsigned index)
This is the default implementation of BufferizableOpInterface::isRepetitiveRegion.
AliasingOpOperandList unknownGetAliasingOpOperands (OpResult opResult)
This is the default implementation of getAliasingOpOperands in case the defining op does not implement the BufferizableOpInterface.
AliasingOpResultList unknownGetAliasingOpResults (OpOperand &opOperand)
This is the default implementation of getAliasingOpResults in case the owner op does not implement the BufferizableOpInterface.
Function Documentation
defaultGetAliasingOpOperands()
AliasingOpOperandList mlir::bufferization::detail::defaultGetAliasingOpOperands (OpResult opResult, const AnalysisState & state)
This is the default implementation of BufferizableOpInterface::getAliasingOpOperands.
Should not be called from other places.
Definition at line 941 of file BufferizableOpInterface.cpp.
defaultGetBufferType()
FailureOr< BaseMemRefType > mlir::bufferization::detail::defaultGetBufferType (Value value, const BufferizationOptions & options, const DenseMap< Value, BaseMemRefType > & fixedTypes)
This is the default implementation of BufferizableOpInterface::getBufferType.
Should not be called from other places.
Definition at line 957 of file BufferizableOpInterface.cpp.
References mlir::bufferization::getMemRefType(), mlir::Value::getType(), mlir::Type::isa(), mlir::Value::isa(), and options.
defaultIsRepetitiveRegion()
bool mlir::bufferization::detail::defaultIsRepetitiveRegion (BufferizableOpInterface bufferizableOp, unsigned index)
This is the default implementation of BufferizableOpInterface::isRepetitiveRegion.
Should not be called from other places.
Definition at line 988 of file BufferizableOpInterface.cpp.
defaultResultBufferizesToMemoryWrite()
bool mlir::bufferization::detail::defaultResultBufferizesToMemoryWrite (OpResult opResult, const AnalysisState & state)
This is the default implementation of BufferizableOpInterface::resultBufferizesToMemoryWrite.
Should not be called from other places.
Definition at line 874 of file BufferizableOpInterface.cpp.
References mlir::bufferization::AnalysisState::bufferizesToMemoryWrite(), mlir::bufferization::AliasList< T >::getAliases(), mlir::Value::getDefiningOp(), and mlir::bufferization::AliasingOpOperand::opOperand.
unknownGetAliasingOpOperands()
AliasingOpOperandList mlir::bufferization::detail::unknownGetAliasingOpOperands (OpResult opResult)
This is the default implementation of getAliasingOpOperands in case the defining op does not implement the BufferizableOpInterface.
Definition at line 999 of file BufferizableOpInterface.cpp.
References mlir::bufferization::AliasList< T >::addAlias(), mlir::Value::getDefiningOp(), mlir::Operation::getOpOperands(), and mlir::bufferization::Unknown.
unknownGetAliasingOpResults()
AliasingOpResultList mlir::bufferization::detail::unknownGetAliasingOpResults (OpOperand & opOperand)
This is the default implementation of getAliasingOpResults in case the owner op does not implement the BufferizableOpInterface.
Definition at line 1009 of file BufferizableOpInterface.cpp.
References mlir::bufferization::AliasList< T >::addAlias(), mlir::Operation::getOpResults(), mlir::detail::IROperandBase::getOwner(), and mlir::bufferization::Unknown.
Referenced by mlir::bufferization::AnalysisState::getAliasingOpResults().