MLIR: mlir::cf Namespace Reference
mlir::cf Namespace Reference
Functions
void populateControlFlowToLLVMConversionPatterns (LLVMTypeConverter &converter, RewritePatternSet &patterns)
Collect the patterns to convert from the ControlFlow dialect to LLVM.
void populateAssertToLLVMConversionPattern (LLVMTypeConverter &converter, RewritePatternSet &patterns, bool abortOnFailure=true)
Populate the cf.assert to LLVM conversion pattern.
void populateControlFlowToSPIRVPatterns (SPIRVTypeConverter &typeConverter, RewritePatternSet &patterns)
Appends to a pattern list additional patterns for translating ControlFLow ops to SPIR-V ops.
Function Documentation
populateAssertToLLVMConversionPattern()
void mlir::cf::populateAssertToLLVMConversionPattern (LLVMTypeConverter & converter, RewritePatternSet & patterns, bool abortOnFailure = true)
Populate the cf.assert to LLVM conversion pattern.
If abortOnFailure is set to false, the program execution continues when a condition is unsatisfied.
Definition at line 254 of file ControlFlowToLLVM.cpp.
References mlir::RewritePatternSet::add().
populateControlFlowToLLVMConversionPatterns()
void mlir::cf::populateControlFlowToLLVMConversionPatterns (LLVMTypeConverter & converter, RewritePatternSet & patterns)
Collect the patterns to convert from the ControlFlow dialect to LLVM.
The conversion patterns capture the LLVMTypeConverter by reference meaning the references have to remain alive during the entire pattern lifetime.
Definition at line 243 of file ControlFlowToLLVM.cpp.
References mlir::RewritePatternSet::add().
populateControlFlowToSPIRVPatterns()
void mlir::cf::populateControlFlowToSPIRVPatterns (SPIRVTypeConverter & typeConverter, RewritePatternSet & patterns)
Appends to a pattern list additional patterns for translating ControlFLow ops to SPIR-V ops.
Definition at line 67 of file ControlFlowToSPIRV.cpp.
References mlir::RewritePatternSet::add(), and mlir::RewritePatternSet::getContext().