MLIR: lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp File Reference
OpenMPToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.h"
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/Dialect/OpenMP/OpenMPInterfaces.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Target/LLVMIR/Dialect/OpenMPCommon.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Frontend/OpenMP/OMPConstants.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/Support/FileSystem.h"
Functions
static llvm::OpenMPIRBuilder::InsertPointTy findAllocaInsertPoint (llvm::IRBuilderBase &builder, const LLVM::ModuleTranslation &moduleTranslation)
Find the insertion point for allocas given the current insertion point for normal operations in the builder.
static llvm::BasicBlock * convertOmpOpRegions (Region &region, StringRef blockName, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, LogicalResult &bodyGenStatus, SmallVectorImpl< llvm::PHINode * > *continuationBlockPHIs=nullptr)
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
static llvm::omp::ProcBindKind getProcBindKind (omp::ClauseProcBindKind kind)
Convert ProcBindKind from MLIR-generated enum to LLVM enum.
static LogicalResult convertOmpParallel (omp::ParallelOp opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts the OpenMP parallel operation to LLVM IR.
static LogicalResult convertOmpMaster (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpCritical (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'critical' operation into LLVM IR using OpenMPIRBuilder.
static omp::ReductionDeclareOp findReductionDecl (omp::WsLoopOp container, omp::ReductionOp reduction)
Returns a reduction declaration that corresponds to the given reduction operation in the given container.
static void collectReductionDecls (omp::WsLoopOp loop, SmallVectorImpl< omp::ReductionDeclareOp > &reductions)
Populates reductions with reduction declarations used in the given loop.
static LogicalResult inlineConvertOmpRegions (Region &region, StringRef blockName, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, SmallVectorImpl< llvm::Value * > *continuationBlockArgs=nullptr)
Translates the blocks contained in the given region and appends them to at the current insertion point of builder.
static OwningReductionGen makeReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Create an OpenMPIRBuilder-compatible reduction generator for the given reduction declaration.
static OwningAtomicReductionGen makeAtomicReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Create an OpenMPIRBuilder-compatible atomic reduction generator for the given reduction declaration.
static LogicalResult convertOmpOrdered (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'ordered' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpOrderedRegion (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'ordered_region' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpSections (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertOmpSingle (omp::SingleOp &singleOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP single construct into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpTaskOp (omp::TaskOp taskOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP task construct into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpTaskgroupOp (omp::TaskGroupOp tgOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP taskgroup construct into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpWsLoop (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpSimdLoop (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP simd loop into LLVM IR using OpenMPIRBuilder.
llvm::AtomicOrdering convertAtomicOrdering (std::optional< omp::ClauseMemoryOrderKind > ao)
Convert an Atomic Ordering attribute to llvm::AtomicOrdering.
static LogicalResult convertOmpAtomicRead (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Convert omp.atomic.read operation to LLVM IR.
static LogicalResult convertOmpAtomicWrite (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an omp.atomic.write operation to LLVM IR.
llvm::AtomicRMWInst::BinOp convertBinOpToAtomic (Operation &op)
Converts an LLVM dialect binary operation to the corresponding enum value for atomicrmw supported binary operation.
static LogicalResult convertOmpAtomicUpdate (omp::AtomicUpdateOp &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP atomic update operation using OpenMPIRBuilder.
static LogicalResult convertOmpAtomicCapture (omp::AtomicCaptureOp atomicCaptureOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertOmpReductionOp (omp::ReductionOp reductionOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP reduction operation using OpenMPIRBuilder.
static LogicalResult convertOmpThreadprivate (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP Threadprivate operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult processMapOperand (llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, const SmallVector< Value > &mapOperands, const ArrayAttr &mapTypes, SmallVector< uint64_t > &mapTypeFlags, SmallVectorImpl< llvm::Constant * > &mapNames, struct llvm::OpenMPIRBuilder::MapperAllocas &mapperAllocas)
Process MapOperands for Target Data directives.
static LogicalResult convertOmpTargetData (Operation *op, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
LogicalResult convertFlagsAttr (Operation *op, mlir::omp::FlagsAttr attribute, LLVM::ModuleTranslation &moduleTranslation)
Lowers the FlagsAttr which is applied to the module on the device pass when offloading, this attribute contains OpenMP RTL globals that can be passed as flags to the frontend, otherwise they are set to default.
static bool getTargetEntryUniqueInfo (llvm::TargetRegionEntryInfo &targetInfo, omp::TargetOp targetOp, llvm::StringRef parentName="")
static bool targetOpSupported (Operation &opInst)
static LogicalResult convertOmpTarget (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Function Documentation
collectReductionDecls()
static void collectReductionDecls (omp::WsLoopOp loop, SmallVectorImpl< omp::ReductionDeclareOp > & reductions) static
Populates reductions with reduction declarations used in the given loop.
Definition at line 404 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpWsLoop().
convertAtomicOrdering()
llvm::AtomicOrdering convertAtomicOrdering (std::optional< omp::ClauseMemoryOrderKind > ao)
Convert an Atomic Ordering attribute to llvm::AtomicOrdering.
Definition at line 1039 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpAtomicCapture(), convertOmpAtomicRead(), convertOmpAtomicUpdate(), and convertOmpAtomicWrite().
convertBinOpToAtomic()
llvm::AtomicRMWInst::BinOp convertBinOpToAtomic (Operation & op)
Converts an LLVM dialect binary operation to the corresponding enum value for atomicrmw supported binary operation.
Definition at line 1101 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpAtomicCapture(), and convertOmpAtomicUpdate().
convertFlagsAttr()
LogicalResult convertFlagsAttr (Operation * op, mlir::omp::FlagsAttr attribute, LLVM::ModuleTranslation & moduleTranslation)
Lowers the FlagsAttr which is applied to the module on the device pass when offloading, this attribute contains OpenMP RTL globals that can be passed as flags to the frontend, otherwise they are set to default.
Definition at line 1548 of file OpenMPToLLVMIRTranslation.cpp.
convertOmpAtomicCapture()
static LogicalResult convertOmpAtomicCapture (omp::AtomicCaptureOp atomicCaptureOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 1186 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Block::begin(), convertAtomicOrdering(), convertBinOpToAtomic(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::LLVM::ModuleTranslation::convertType(), mlir::Operation::emitError(), mlir::failed(), findAllocaInsertPoint(), mlir::Operation::getNumOperands(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Block::getTerminator(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapBlock(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertOmpAtomicRead()
static LogicalResult convertOmpAtomicRead (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Convert omp.atomic.read operation to LLVM IR.
Definition at line 1060 of file OpenMPToLLVMIRTranslation.cpp.
References convertAtomicOrdering(), mlir::LLVM::ModuleTranslation::convertType(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpAtomicUpdate()
static LogicalResult convertOmpAtomicUpdate (omp::AtomicUpdateOp & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP atomic update operation using OpenMPIRBuilder.
Definition at line 1117 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Block::begin(), convertAtomicOrdering(), convertBinOpToAtomic(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::LLVM::ModuleTranslation::convertType(), mlir::Operation::emitError(), mlir::failed(), findAllocaInsertPoint(), mlir::Operation::getNumOperands(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Operation::getOperand(), mlir::Operation::getOperands(), mlir::Block::getTerminator(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapBlock(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertOmpAtomicWrite()
static LogicalResult convertOmpAtomicWrite (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an omp.atomic.write operation to LLVM IR.
Definition at line 1083 of file OpenMPToLLVMIRTranslation.cpp.
References convertAtomicOrdering(), mlir::LLVM::ModuleTranslation::convertType(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpCritical()
static LogicalResult convertOmpCritical (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'critical' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 342 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::get(), mlir::LLVM::ModuleTranslation::getLLVMContext(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpMaster()
static LogicalResult convertOmpMaster (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 315 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpOpRegions()
static llvm::BasicBlock* convertOmpOpRegions (Region & region, StringRef blockName, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, LogicalResult & bodyGenStatus, SmallVectorImpl< llvm::PHINode * > * continuationBlockPHIs = nullptr) static
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
Populates continuationBlockPHIs with the PHI nodes of the continuation block if provided.
Definition at line 127 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::detail::connectPHINodes(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::forgetMapping(), mlir::Region::getBlocks(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::LLVM::detail::getTopologicallySortedBlocks(), mlir::LLVM::ModuleTranslation::lookupBlock(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::LLVM::ModuleTranslation::mapBlock().
Referenced by convertOmpCritical(), convertOmpMaster(), convertOmpOrderedRegion(), convertOmpParallel(), convertOmpSimdLoop(), convertOmpSingle(), convertOmpTarget(), convertOmpTaskgroupOp(), convertOmpTaskOp(), convertOmpWsLoop(), and inlineConvertOmpRegions().
convertOmpOrdered()
static LogicalResult convertOmpOrdered (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'ordered' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 538 of file OpenMPToLLVMIRTranslation.cpp.
References findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValues(), and mlir::success().
convertOmpOrderedRegion()
static LogicalResult convertOmpOrderedRegion (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'ordered_region' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 568 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::failure(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpParallel()
static LogicalResult convertOmpParallel (omp::ParallelOp opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts the OpenMP parallel operation to LLVM IR.
Definition at line 257 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), getProcBindKind(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpReductionOp()
static LogicalResult convertOmpReductionOp (omp::ReductionOp reductionOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP reduction operation using OpenMPIRBuilder.
Expects the mapping between reduction variables and their private equivalents to have been stored on the ModuleTranslation stack. Currently only supports reduction within WsLoopOp, but can be easily extended.
Definition at line 1280 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), mlir::failure(), findReductionDecl(), mlir::Region::front(), mlir::Block::getArgument(), inlineConvertOmpRegions(), mlir::WalkResult::interrupt(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::LLVM::ModuleTranslation::stackWalk(), and mlir::success().
convertOmpSections()
static LogicalResult convertOmpSections (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 601 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::emitError(), and mlir::success().
convertOmpSimdLoop()
static LogicalResult convertOmpSimdLoop (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP simd loop into LLVM IR using OpenMPIRBuilder.
Definition at line 952 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
convertOmpSingle()
static LogicalResult convertOmpSingle (omp::SingleOp & singleOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP single construct into LLVM IR using OpenMPIRBuilder.
Definition at line 669 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpTarget()
static LogicalResult convertOmpTarget (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 1626 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::failure(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Operation::getParentOfType(), getTargetEntryUniqueInfo(), mlir::getUsedValuesDefinedAbove(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::success(), and targetOpSupported().
convertOmpTargetData()
static LogicalResult convertOmpTargetData (Operation * op, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 1424 of file OpenMPToLLVMIRTranslation.cpp.
convertOmpTaskgroupOp()
static LogicalResult convertOmpTaskgroupOp (omp::TaskGroupOp tgOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP taskgroup construct into LLVM IR using OpenMPIRBuilder.
Definition at line 737 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
convertOmpTaskOp()
static LogicalResult convertOmpTaskOp (omp::TaskOp taskOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP task construct into LLVM IR using OpenMPIRBuilder.
Definition at line 687 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
convertOmpThreadprivate()
static LogicalResult convertOmpThreadprivate (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP Threadprivate operation into LLVM IR using OpenMPIRBuilder.
Definition at line 1327 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Operation::emitError(), mlir::Value::getDefiningOp(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::Operation::getResult(), mlir::LLVM::ModuleTranslation::lookupGlobal(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::success(), and mlir::LLVM::ModuleTranslation::symbolTable().
convertOmpWsLoop()
static LogicalResult convertOmpWsLoop (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
Definition at line 758 of file OpenMPToLLVMIRTranslation.cpp.
References collectReductionDecls(), convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), mlir::failure(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), inlineConvertOmpRegions(), mlir::LLVM::ModuleTranslation::lookupValue(), makeAtomicReductionGen(), makeReductionGen(), mlir::LLVM::ModuleTranslation::mapValue(), and mlir::success().
findAllocaInsertPoint()
static llvm::OpenMPIRBuilder::InsertPointTy findAllocaInsertPoint (llvm::IRBuilderBase & builder, const LLVM::ModuleTranslation & moduleTranslation) static
Find the insertion point for allocas given the current insertion point for normal operations in the builder.
Definition at line 84 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::WalkResult::interrupt(), mlir::LLVM::ModuleTranslation::stackWalk(), and mlir::WalkResult::wasInterrupted().
Referenced by convertOmpAtomicCapture(), convertOmpAtomicUpdate(), convertOmpOrdered(), convertOmpParallel(), convertOmpTaskgroupOp(), convertOmpTaskOp(), and convertOmpWsLoop().
findReductionDecl()
static omp::ReductionDeclareOp findReductionDecl (omp::WsLoopOp container, omp::ReductionOp reduction) static
Returns a reduction declaration that corresponds to the given reduction operation in the given container.
Currently only supports reductions inside WsLoopOp but can be easily extended.
Definition at line 386 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpReductionOp().
getProcBindKind()
static llvm::omp::ProcBindKind getProcBindKind (omp::ClauseProcBindKind kind) static
Convert ProcBindKind from MLIR-generated enum to LLVM enum.
Definition at line 241 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpParallel().
getTargetEntryUniqueInfo()
static bool getTargetEntryUniqueInfo (llvm::TargetRegionEntryInfo & targetInfo, omp::TargetOp targetOp, llvm::StringRef parentName = "") static
Definition at line 1580 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpTarget().
inlineConvertOmpRegions()
static LogicalResult inlineConvertOmpRegions (Region & region, StringRef blockName, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, SmallVectorImpl< llvm::Value * > * continuationBlockArgs = nullptr) static
Translates the blocks contained in the given region and appends them to at the current insertion point of builder.
The operations of the entry block are appended to the current insertion block, which is not expected to have a terminator. If set, continuationBlockArgs is populated with translated values that correspond to the values omp.yield'ed from the region.
Definition at line 423 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Block::back(), mlir::LLVM::ModuleTranslation::convertBlock(), convertOmpOpRegions(), mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::forgetMapping(), mlir::Region::front(), mlir::Operation::getOperands(), mlir::LLVM::ModuleTranslation::lookupValues(), mlir::LLVM::ModuleTranslation::mapBlock(), and mlir::success().
Referenced by convertOmpReductionOp(), convertOmpWsLoop(), makeAtomicReductionGen(), and makeReductionGen().
makeAtomicReductionGen()
static OwningAtomicReductionGen makeAtomicReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Create an OpenMPIRBuilder-compatible atomic reduction generator for the given reduction declaration.
The generator uses builder but ignores its insertion point. Returns null if there is no atomic region available in the reduction declaration.
Definition at line 509 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::failed(), mlir::Region::front(), mlir::Block::getArgument(), inlineConvertOmpRegions(), and mlir::LLVM::ModuleTranslation::mapValue().
Referenced by convertOmpWsLoop().
makeReductionGen()
static OwningReductionGen makeReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Create an OpenMPIRBuilder-compatible reduction generator for the given reduction declaration.
The generator uses builder but ignores its insertion point.
Definition at line 479 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::failed(), mlir::Region::front(), mlir::Block::getArgument(), inlineConvertOmpRegions(), and mlir::LLVM::ModuleTranslation::mapValue().
Referenced by convertOmpWsLoop().
processMapOperand()
static LogicalResult processMapOperand (llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, const SmallVector< Value > & mapOperands, const ArrayAttr & mapTypes, SmallVector< uint64_t > & mapTypeFlags, SmallVectorImpl< llvm::Constant * > & mapNames, struct llvm::OpenMPIRBuilder::MapperAllocas & mapperAllocas) static
Process MapOperands for Target Data directives.
Definition at line 1360 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::createMappingInformation(), mlir::failure(), mlir::get(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
targetOpSupported()
static bool targetOpSupported (Operation & opInst) static
Definition at line 1600 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Operation::emitError().
Referenced by convertOmpTarget().