MLIR: lib/Dialect/SparseTensor/Transforms/SparseTensorRewriting.cpp File Reference
SparseTensorRewriting.cpp File Reference
#include "CodegenUtils.h"
#include "LoopEmitter.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorType.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Support/LLVM.h"
Functions
static bool isZeroValue (Value val)
static bool isSparseTensor (OpOperand *op)
static bool isAlloc (OpOperand *op, bool isZero)
static bool isSampling (GenericOp op)
static bool isMulChain (Value val, Value x)
static bool isSumOfMul (GenericOp op)
static bool isZeroYield (GenericOp op)
static void sizesForTensor (OpBuilder &builder, SmallVectorImpl< Value > &sizes, Location loc, ShapedType stp, Value tensor)
Populates given sizes array from type (for static sizes) and from the tensor (for dynamic sizes).
static RankedTensorType getUnorderedCOOFromTypeWithOrdering (RankedTensorType src, AffineMap ordering)
static RankedTensorType getUnorderedCOOFromType (RankedTensorType src)
static void getDynamicSizes (RankedTensorType tp, const SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &dynSizes)
Collects the dynamic dimension sizes for tp with the assumption that sizes are the dimension sizes for the type.
static LogicalResult genForeachOnSparseConstant (ForeachOp op, RewriterBase &rewriter, SparseElementsAttr attr)
static void concatSizesFromInputs (OpBuilder &builder, SmallVectorImpl< Value > &sizes, Location loc, ShapedType dstTp, ValueRange srcs, unsigned dim)
Populates the given sizes array for concatenation from types (for static sizes) and from the source tensors (for dynamic sizes).
Function Documentation
concatSizesFromInputs()
static void concatSizesFromInputs (OpBuilder & builder, SmallVectorImpl< Value > & sizes, Location loc, ShapedType dstTp, ValueRange srcs, unsigned dim) static
Populates the given sizes array for concatenation from types (for static sizes) and from the source tensors (for dynamic sizes).
Definition at line 184 of file SparseTensorRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), mlir::linalg::createOrFoldDimOp(), and mlir::sparse_tensor::sizesFromSrc().
genForeachOnSparseConstant()
static LogicalResult genForeachOnSparseConstant (ForeachOp op, RewriterBase & rewriter, SparseElementsAttr attr) static
Definition at line 153 of file SparseTensorRewriting.cpp.
getDynamicSizes()
static void getDynamicSizes (RankedTensorType tp, const SmallVectorImpl< Value > & sizes, SmallVectorImpl< Value > & dynSizes) static
Collects the dynamic dimension sizes for tp with the assumption that sizes are the dimension sizes for the type.
Stores the dynamic dimension sizes to dynSizes.
Definition at line 144 of file SparseTensorRewriting.cpp.
References mlir::detail::enumerate().
getUnorderedCOOFromType()
static RankedTensorType getUnorderedCOOFromType (RankedTensorType src) static
Definition at line 137 of file SparseTensorRewriting.cpp.
References mlir::sparse_tensor::getCOOFromType().
getUnorderedCOOFromTypeWithOrdering()
static RankedTensorType getUnorderedCOOFromTypeWithOrdering (RankedTensorType src, AffineMap ordering) static
Definition at line 133 of file SparseTensorRewriting.cpp.
References mlir::sparse_tensor::getCOOFromTypeWithOrdering().
isAlloc()
static bool isAlloc (OpOperand * op, bool isZero) static
Definition at line 52 of file SparseTensorRewriting.cpp.
isMulChain()
static bool isMulChain (Value val, Value x) static
Definition at line 81 of file SparseTensorRewriting.cpp.
References mlir::Value::dyn_cast(), and mlir::Value::getDefiningOp().
isSampling()
static bool isSampling (GenericOp op) static
Definition at line 66 of file SparseTensorRewriting.cpp.
isSparseTensor()
static bool isSparseTensor (OpOperand * op) static
Definition at line 45 of file SparseTensorRewriting.cpp.
isSumOfMul()
static bool isSumOfMul (GenericOp op) static
Definition at line 93 of file SparseTensorRewriting.cpp.
isZeroValue()
static bool isZeroValue (Value val) static
Definition at line 40 of file SparseTensorRewriting.cpp.
References mlir::m_AnyZeroFloat(), mlir::m_Zero(), and mlir::matchPattern().
isZeroYield()
static bool isZeroYield (GenericOp op) static
Definition at line 106 of file SparseTensorRewriting.cpp.
sizesForTensor()
static void sizesForTensor (OpBuilder & builder, SmallVectorImpl< Value > & sizes, Location loc, ShapedType stp, Value tensor) static
Populates given sizes array from type (for static sizes) and from the tensor (for dynamic sizes).
Definition at line 118 of file SparseTensorRewriting.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::OpBuilder::create(), and mlir::detail::enumerate().