MLIR: lib/Dialect/SparseTensor/Transforms/SparseTensorStorageLayout.cpp File Reference
SparseTensorStorageLayout.cpp File Reference
#include "SparseTensorStorageLayout.h"
#include "CodegenUtils.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/Dialect/SparseTensor/Transforms/Passes.h"
#include "mlir/Transforms/DialectConversion.h"
Macros
#define RETURN_ON_FALSE(fidx, kind, dim, dlt)
Functions
static IntegerAttr optionalLevelAttr (MLIRContext *ctx, std::optional< Level > lvl)
Constructs a nullable LevelAttr from the std::optional<Level>.
static std::optional< LogicalResult > convertSparseTensorType (RankedTensorType rtp, SmallVectorImpl< Type > &fields)
Variables
constexpr FieldIndex kDataFieldStartingIdx = 0
Macro Definition Documentation
RETURN_ON_FALSE
#define RETURN_ON_FALSE (fidx, kind, dim, dlt)
Value:
  if (!(callback(fidx, kind, dim, dlt)))                                       \
    return;
Function Documentation
convertSparseTensorType()
static std::optional<LogicalResult> convertSparseTensorType (RankedTensorType rtp, SmallVectorImpl< Type > & fields) static
Definition at line 36 of file SparseTensorStorageLayout.cpp.
References mlir::sparse_tensor::foreachFieldAndTypeInSparseTensor(), mlir::sparse_tensor::SparseTensorType::hasEncoding(), and mlir::success().
Referenced by mlir::SparseTensorTypeToBufferConverter::SparseTensorTypeToBufferConverter().
optionalLevelAttr()
static IntegerAttr optionalLevelAttr (MLIRContext * ctx, std::optional< Level > lvl) static
Constructs a nullable LevelAttr from the std::optional<Level>.
Definition at line 26 of file SparseTensorStorageLayout.cpp.
References mlir::get().
Variable Documentation
kDataFieldStartingIdx
constexpr FieldIndex kDataFieldStartingIdx = 0 constexpr
Definition at line 124 of file SparseTensorStorageLayout.cpp.
Referenced by mlir::sparse_tensor::foreachFieldInSparseTensor(), and mlir::sparse_tensor::getNumDataFieldsFromEncoding().