MLIR: lib/Dialect/Linalg/Transforms/SubsetHoisting.cpp File Reference
SubsetHoisting.cpp File Reference
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Linalg/Transforms/Hoisting.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/Dialect/SCF/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/Dialect/Vector/IR/VectorOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/LoopInvariantCodeMotionUtils.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "subset-hoisting"
#define DBGS() (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Functions
static bool isSubsetLocationLoopInvariant (scf::ForOp forOp, vector::TransferWriteOp transferWriteOp)
Return true if the location of the subset defined by the op is invariant of the loop iteration.
static bool isSubsetLocationLoopInvariant (scf::ForOp forOp, tensor::InsertSliceOp insertSliceOp)
Return true if the location of the subset defined by the op is invariant of the loop iteration.
static FailureOr< tensor::ExtractSliceOp > findHoistableMatchingExtractSlice (RewriterBase &rewriter, tensor::InsertSliceOp insertSliceOp, BlockArgument srcTensor)
Given an srcTensor that is a block argument belong to a loop.
static FailureOr< vector::TransferReadOp > findHoistableMatchingTransferRead (RewriterBase &rewriter, vector::TransferWriteOp transferWriteOp, BlockArgument srcTensor)
Given an srcTensor that is a block argument belong to a loop.
static FailureOr< vector::TransferWriteOp > getLoopInvariantTransferWriteDefining (RewriterBase &rewriter, scf::ForOp forOp, BlockArgument bbArg, OpOperand &yieldOperand)
Return the vector.transfer_write that produces yieldOperand, if:
static FailureOr< tensor::InsertSliceOp > getLoopInvariantInsertSliceDefining (RewriterBase &rewriter, scf::ForOp forOp, BlockArgument bbArg, OpOperand &yieldOperand)
Return the tensor.insert_slice that produces yieldOperand, if:
static Operation * isTensorChunkAccessedByUnknownOp (Operation *writeOp, Operation *candidateReadOp, BlockArgument tensorArg)
Check if the chunk of data inserted by the writeOp is read by any other op than the candidateReadOp.
static scf::ForOp hoistTransferReadWrite (RewriterBase &rewriter, vector::TransferReadOp transferReadOp, vector::TransferWriteOp transferWriteOp, BlockArgument tensorBBArg)
Mechanical hoisting of a matching read / write pair.
static scf::ForOp hoistExtractInsertSlice (RewriterBase &rewriter, tensor::ExtractSliceOp extractSliceOp, tensor::InsertSliceOp insertSliceOp, BlockArgument tensorBBArg)
Mechanical hoisting of a matching read / write pair.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << '[' << DEBUG_TYPE << "] ")
Definition at line 30 of file SubsetHoisting.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "subset-hoisting"
Definition at line 28 of file SubsetHoisting.cpp.
Function Documentation
findHoistableMatchingExtractSlice()
static FailureOr<tensor::ExtractSliceOp> findHoistableMatchingExtractSlice (RewriterBase & rewriter, tensor::InsertSliceOp insertSliceOp, BlockArgument srcTensor) static
Given an srcTensor that is a block argument belong to a loop.
Greedily look for the first read that can be hoisted out of the loop (i.e. that satisfied the conditions):
The read is of type tensor.extract_slice.
The read is one of the uses of srcTensor.
The read is to the same subset that tensor.insert_slice writes.
Definition at line 65 of file SubsetHoisting.cpp.
References DBGS, mlir::failure(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Value::getUsers(), and mlir::Type::isa().
Referenced by mlir::linalg::hoistRedundantSubsetExtractInsert().
findHoistableMatchingTransferRead()
static FailureOr<vector::TransferReadOp> findHoistableMatchingTransferRead (RewriterBase & rewriter, vector::TransferWriteOp transferWriteOp, BlockArgument srcTensor) static
Given an srcTensor that is a block argument belong to a loop.
Greedily look for the first read that can be hoisted out of the loop (i.e. that satisfied the conditions):
The read is of type tensor.transfer_read.
The read is one of the uses of srcTensor.
The read is to the same subset that tensor.transfer_write writes.
Definition at line 119 of file SubsetHoisting.cpp.
References DBGS, mlir::failure(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Operation::getUsers(), mlir::Value::getUsers(), mlir::Type::isa(), mlir::vector::isDisjointTransferIndices(), and mlir::RewriterBase::notifyMatchFailure().
Referenced by mlir::linalg::hoistRedundantSubsetExtractInsert().
getLoopInvariantInsertSliceDefining()
static FailureOr<tensor::InsertSliceOp> getLoopInvariantInsertSliceDefining (RewriterBase & rewriter, scf::ForOp forOp, BlockArgument bbArg, OpOperand & yieldOperand) static
Return the tensor.insert_slice that produces yieldOperand, if:
Its destination tensor is a block argument of the forOp.
The unique use of its result is a yield with operand number matching the block argument.
All indices are defined outside of the loop. Return failure otherwise.
This is sufficient condition to hoist the tensor.insert_slice; other operands can always be yielded by the loop where needed. Note: 1. + 2. ensure that the yield / iter_args cycle results in proper semantics (i.e. no ping-ping between iter_args across iterations).
Definition at line 242 of file SubsetHoisting.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), isSubsetLocationLoopInvariant(), and mlir::RewriterBase::notifyMatchFailure().
Referenced by mlir::linalg::hoistRedundantSubsetExtractInsert().
getLoopInvariantTransferWriteDefining()
static FailureOr<vector::TransferWriteOp> getLoopInvariantTransferWriteDefining (RewriterBase & rewriter, scf::ForOp forOp, BlockArgument bbArg, OpOperand & yieldOperand) static
Return the vector.transfer_write that produces yieldOperand, if:
The write operates on tensors.
All indices are defined outside of the loop. Return failure otherwise.
This is sufficient condition to hoist the vector.transfer_write; other operands can always be yielded by the loop where needed.
Definition at line 198 of file SubsetHoisting.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::OpOperand::getOperandNumber(), mlir::detail::IROperandBase::getOwner(), isSubsetLocationLoopInvariant(), and mlir::RewriterBase::notifyMatchFailure().
Referenced by mlir::linalg::hoistRedundantSubsetExtractInsert().
hoistExtractInsertSlice()
static scf::ForOp hoistExtractInsertSlice (RewriterBase & rewriter, tensor::ExtractSliceOp extractSliceOp, tensor::InsertSliceOp insertSliceOp, BlockArgument tensorBBArg) static
Mechanical hoisting of a matching read / write pair.
Return the newly created scf::ForOp with an extra yields.
Definition at line 399 of file SubsetHoisting.cpp.
References DBGS, mlir::RewriterBase::eraseOp(), mlir::RewriterBase::finalizeRootUpdate(), mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::RewriterBase::replaceAllUsesExcept(), mlir::replaceLoopWithNewYields(), and mlir::RewriterBase::startRootUpdate().
Referenced by mlir::linalg::hoistRedundantSubsetExtractInsert().
hoistTransferReadWrite()
static scf::ForOp hoistTransferReadWrite (RewriterBase & rewriter, vector::TransferReadOp transferReadOp, vector::TransferWriteOp transferWriteOp, BlockArgument tensorBBArg) static
Mechanical hoisting of a matching read / write pair.
Return the newly created scf::ForOp with an extra yields.
Definition at line 340 of file SubsetHoisting.cpp.
References DBGS, mlir::RewriterBase::eraseOp(), mlir::RewriterBase::finalizeRootUpdate(), mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), mlir::Block::getParentOp(), mlir::RewriterBase::replaceAllUsesExcept(), mlir::replaceLoopWithNewYields(), and mlir::RewriterBase::startRootUpdate().
Referenced by mlir::linalg::hoistRedundantSubsetExtractInsert().
isSubsetLocationLoopInvariant() [1/2]
static bool isSubsetLocationLoopInvariant (scf::ForOp forOp, tensor::InsertSliceOp insertSliceOp) static
Return true if the location of the subset defined by the op is invariant of the loop iteration.
Definition at line 48 of file SubsetHoisting.cpp.
isSubsetLocationLoopInvariant() [2/2]
static bool isSubsetLocationLoopInvariant (scf::ForOp forOp, vector::TransferWriteOp transferWriteOp) static
Return true if the location of the subset defined by the op is invariant of the loop iteration.
Definition at line 38 of file SubsetHoisting.cpp.
Referenced by getLoopInvariantInsertSliceDefining(), and getLoopInvariantTransferWriteDefining().
isTensorChunkAccessedByUnknownOp()
static Operation* isTensorChunkAccessedByUnknownOp (Operation * writeOp, Operation * candidateReadOp, BlockArgument tensorArg) static
Check if the chunk of data inserted by the writeOp is read by any other op than the candidateReadOp.
This conflicting operation prevents hoisting, return it or nullptr if none is found.
Definition at line 274 of file SubsetHoisting.cpp.
References mlir::Operation::getParentOp(), mlir::Value::getUses(), mlir::Operation::isAncestor(), and mlir::vector::isDisjointTransferIndices().
Referenced by mlir::linalg::hoistRedundantSubsetExtractInsert().