MLIR: lib/CAPI/Dialect/Transform.cpp File Reference
Transform.cpp File Reference
#include "mlir-c/Dialect/Transform.h"
#include "mlir-c/Support.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformTypes.h"
Functions
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION (Transform, transform, transform::TransformDialect) bool mlirTypeIsATransformAnyOpType(MlirType type)
MlirType mlirTransformAnyOpTypeGet (MlirContext ctx)
bool mlirTypeIsATransformOperationType (MlirType type)
MlirType mlirTransformOperationTypeGet (MlirContext ctx, MlirStringRef operationName)
MlirStringRef mlirTransformOperationTypeGetOperationName (MlirType type)
Function Documentation
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION()
MLIR_DEFINE_CAPI_DIALECT_REGISTRATION (Transform , transform , transform::TransformDialect)
Definition at line 17 of file Transform.cpp.
References unwrap().
mlirTransformAnyOpTypeGet()
MlirType mlirTransformAnyOpTypeGet (MlirContext ctx)
Definition at line 28 of file Transform.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformOperationTypeGet()
MlirType mlirTransformOperationTypeGet (MlirContext ctx, MlirStringRef operationName)
Definition at line 40 of file Transform.cpp.
References mlir::get(), unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTransformOperationTypeGetOperationName()
MlirStringRef mlirTransformOperationTypeGetOperationName (MlirType type)
Definition at line 46 of file Transform.cpp.
References unwrap(), and wrap().
Referenced by populateDialectTransformSubmodule().
mlirTypeIsATransformOperationType()
bool mlirTypeIsATransformOperationType (MlirType type)
Definition at line 36 of file Transform.cpp.
References unwrap().
Referenced by populateDialectTransformSubmodule().