MLIR: lib/Dialect/Transform/Transforms/TransformInterpreterPassBase.cpp File Reference
TransformInterpreterPassBase.cpp File Reference
#include "mlir/Dialect/Transform/Transforms/TransformInterpreterPassBase.h"
#include "mlir/Dialect/Transform/IR/TransformDialect.h"
#include "mlir/Dialect/Transform/IR/TransformInterfaces.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/FunctionInterfaces.h"
#include "mlir/IR/Verifier.h"
#include "mlir/IR/Visitors.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "transform-dialect-interpreter"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
#define DEBUG_TYPE_DUMP_STDERR "transform-dialect-dump-repro"
#define DEBUG_TYPE_DUMP_FILE "transform-dialect-save-repro"
Functions
static LogicalResult parseTransformModuleFromFile (MLIRContext *context, llvm::StringRef transformFileName, OwningOpRef< ModuleOp > &transformModule)
Utility to parse the content of a transformFileName MLIR file containing a transform dialect specification.
static Operation * findTopLevelTransform (Operation *root, StringRef filenameOption)
Finds the single top-level transform operation with root as ancestor.
static Operation * findOpWithTag (Operation *root, StringRef tagKey, StringRef tagValue)
Finds an operation nested in root that has the transform dialect tag attribute with the value specified as tag.
static Operation * getRootOperation (Operation *target)
Returns the ancestor of target that doesn't have a parent.
static llvm::raw_ostream & printReproCall (llvm::raw_ostream &os, StringRef rootOpName, StringRef passName, const Pass::Option< std::string > &debugPayloadRootTag, const Pass::Option< std::string > &debugTransformRootTag, const Pass::Option< std::string > &transformLibraryFileName, StringRef binaryName)
Prints the CLI command running the repro with the current path.
llvm::raw_ostream & printModuleForRepro (llvm::raw_ostream &os, Operation *root, Operation *transform)
Prints the module rooted at root to os and appends transformContainer if it is not nested in root.
void saveReproToTempFile (llvm::raw_ostream &os, Operation *target, Operation *transform, StringRef passName, const Pass::Option< std::string > &debugPayloadRootTag, const Pass::Option< std::string > &debugTransformRootTag, const Pass::Option< std::string > &transformLibraryFileName, StringRef binaryName)
Saves the payload and the transform IR into a temporary file and reports the file name to os.
static void performOptionalDebugActions (Operation *target, Operation *transform, StringRef passName, const Pass::Option< std::string > &debugPayloadRootTag, const Pass::Option< std::string > &debugTransformRootTag, const Pass::Option< std::string > &transformLibraryFileName, StringRef binaryName)
static LogicalResult defineDeclaredSymbols (Block &block, ModuleOp definitions)
Replaces external symbols in block with their (non-external) definitions from the given module.
Variables
constexpr static llvm::StringLiteral kTransformDialectTagAttrName
Name of the attribute used for targeting the transform dialect interpreter at specific operations.
constexpr static llvm::StringLiteral kTransformDialectTagPayloadRootValue
Value of the attribute indicating the root payload operation.
constexpr static llvm::StringLiteral kTransformDialectTagTransformContainerValue = "transform_container"
Value of the attribute indicating the container of transform operations (containing the top-level transform operation).
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Definition at line 37 of file TransformInterpreterPassBase.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "transform-dialect-interpreter"
Definition at line 36 of file TransformInterpreterPassBase.cpp.
DEBUG_TYPE_DUMP_FILE
#define DEBUG_TYPE_DUMP_FILE "transform-dialect-save-repro"
Definition at line 39 of file TransformInterpreterPassBase.cpp.
DEBUG_TYPE_DUMP_STDERR
#define DEBUG_TYPE_DUMP_STDERR "transform-dialect-dump-repro"
Definition at line 38 of file TransformInterpreterPassBase.cpp.
Function Documentation
defineDeclaredSymbols()
static LogicalResult defineDeclaredSymbols (Block & block, ModuleOp definitions) static
Replaces external symbols in block with their (non-external) definitions from the given module.
Definition at line 301 of file TransformInterpreterPassBase.cpp.
References mlir::get().
Referenced by mlir::transform::detail::interpreterBaseInitializeImpl(), and mlir::transform::detail::interpreterBaseRunOnOperationImpl().
findOpWithTag()
static Operation* findOpWithTag (Operation * root, StringRef tagKey, StringRef tagValue) static
Finds an operation nested in root that has the transform dialect tag attribute with the value specified as tag.
Assumes only one operation may have the tag. Returns nullptr if there is no such operation.
Definition at line 118 of file TransformInterpreterPassBase.cpp.
References mlir::PreOrder, and mlir::Operation::walk().
Referenced by mlir::transform::detail::interpreterBaseRunOnOperationImpl().
findTopLevelTransform()
static Operation* findTopLevelTransform (Operation * root, StringRef filenameOption) static
Finds the single top-level transform operation with root as ancestor.
Reports an error if there is more than one such operation and returns the first one found. Reports an error returns nullptr if no such operation found.
Definition at line 85 of file TransformInterpreterPassBase.cpp.
References diag(), mlir::Operation::emitError(), mlir::WalkResult::interrupt(), mlir::PreOrder, mlir::WalkResult::skip(), mlir::Operation::walk(), and mlir::WalkResult::wasInterrupted().
Referenced by mlir::transform::detail::interpreterBaseRunOnOperationImpl().
getRootOperation()
static Operation* getRootOperation (Operation * target) static
Returns the ancestor of target that doesn't have a parent.
Definition at line 150 of file TransformInterpreterPassBase.cpp.
References mlir::Operation::getParentOp().
Referenced by performOptionalDebugActions(), and saveReproToTempFile().
parseTransformModuleFromFile()
static LogicalResult parseTransformModuleFromFile (MLIRContext * context, llvm::StringRef transformFileName, OwningOpRef< ModuleOp > & transformModule) static
Utility to parse the content of a transformFileName MLIR file containing a transform dialect specification.
Definition at line 56 of file TransformInterpreterPassBase.cpp.
References DBGS, mlir::emitError(), mlir::get(), mlir::openInputFile(), and mlir::success().
Referenced by mlir::transform::detail::interpreterBaseInitializeImpl().
performOptionalDebugActions()
static void performOptionalDebugActions (Operation * target, Operation * transform, StringRef passName, const Pass::Option< std::string > & debugPayloadRootTag, const Pass::Option< std::string > & debugTransformRootTag, const Pass::Option< std::string > & transformLibraryFileName, StringRef binaryName) static
Definition at line 237 of file TransformInterpreterPassBase.cpp.
References DEBUG_TYPE_DUMP_FILE, DEBUG_TYPE_DUMP_STDERR, mlir::get(), mlir::Operation::getContext(), mlir::Operation::getName(), getRootOperation(), mlir::OperationName::getStringRef(), mlir::MLIRContext::isMultithreadingEnabled(), kTransformDialectTagAttrName, kTransformDialectTagPayloadRootValue, kTransformDialectTagTransformContainerValue, printModuleForRepro(), printReproCall(), saveReproToTempFile(), and mlir::Operation::setAttr().
Referenced by mlir::transform::detail::interpreterBaseRunOnOperationImpl().
printModuleForRepro()
llvm::raw_ostream& printModuleForRepro (llvm::raw_ostream & os, Operation * root, Operation * transform)
Prints the module rooted at root to os and appends transformContainer if it is not nested in root.
Definition at line 189 of file TransformInterpreterPassBase.cpp.
References mlir::Operation::isAncestor(), and mlir::Operation::print().
Referenced by performOptionalDebugActions(), and saveReproToTempFile().
printReproCall()
static llvm::raw_ostream& printReproCall (llvm::raw_ostream & os, StringRef rootOpName, StringRef passName, const Pass::Option< std::string > & debugPayloadRootTag, const Pass::Option< std::string > & debugTransformRootTag, const Pass::Option< std::string > & transformLibraryFileName, StringRef binaryName) static
Prints the CLI command running the repro with the current path.
Definition at line 161 of file TransformInterpreterPassBase.cpp.
References kTransformDialectTagPayloadRootValue, and kTransformDialectTagTransformContainerValue.
Referenced by performOptionalDebugActions(), and saveReproToTempFile().
saveReproToTempFile()
void saveReproToTempFile (llvm::raw_ostream & os, Operation * target, Operation * transform, StringRef passName, const Pass::Option< std::string > & debugPayloadRootTag, const Pass::Option< std::string > & debugTransformRootTag, const Pass::Option< std::string > & transformLibraryFileName, StringRef binaryName)
Saves the payload and the transform IR into a temporary file and reports the file name to os.
Definition at line 199 of file TransformInterpreterPassBase.cpp.
References mlir::Operation::getName(), getRootOperation(), mlir::OperationName::getStringRef(), printModuleForRepro(), and printReproCall().
Referenced by performOptionalDebugActions().
Variable Documentation
kTransformDialectTagAttrName
constexpr static llvm::StringLiteral kTransformDialectTagAttrName static constexpr
Initial value:
=
    "transform.target_tag"
Name of the attribute used for targeting the transform dialect interpreter at specific operations.
Definition at line 43 of file TransformInterpreterPassBase.cpp.
Referenced by mlir::transform::detail::interpreterBaseRunOnOperationImpl(), and performOptionalDebugActions().
kTransformDialectTagPayloadRootValue
constexpr static llvm::StringLiteral kTransformDialectTagPayloadRootValue static constexpr
Initial value:
=
    "payload_root"
Value of the attribute indicating the root payload operation.
Definition at line 46 of file TransformInterpreterPassBase.cpp.
Referenced by performOptionalDebugActions(), and printReproCall().
kTransformDialectTagTransformContainerValue
constexpr static llvm::StringLiteral kTransformDialectTagTransformContainerValue = "transform_container" static constexpr
Value of the attribute indicating the container of transform operations (containing the top-level transform operation).
Definition at line 51 of file TransformInterpreterPassBase.cpp.
Referenced by performOptionalDebugActions(), and printReproCall().