MLIR: lib/Dialect/Utils/IndexingUtils.cpp File Reference
IndexingUtils.cpp File Reference
#include "mlir/Dialect/Utils/IndexingUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/MLIRContext.h"
#include "llvm/ADT/STLExtras.h"
#include <numeric>
#include <optional>
Functions
template<typename ExprType >
SmallVector< ExprType > computeSuffixProductImpl (ArrayRef< ExprType > sizes, ExprType unit)
template<typename ExprType >
SmallVector< ExprType > computeElementwiseMulImpl (ArrayRef< ExprType > v1, ArrayRef< ExprType > v2)
template<typename ExprType >
ExprType linearizeImpl (ArrayRef< ExprType > offsets, ArrayRef< ExprType > basis, ExprType zero)
template<typename ExprType , typename DivOpTy >
SmallVector< ExprType > delinearizeImpl (ExprType linearIndex, ArrayRef< ExprType > strides, DivOpTy divOp)
Function Documentation
computeElementwiseMulImpl()
template<typename ExprType > SmallVector<ExprType> computeElementwiseMulImpl (ArrayRef< ExprType > v1, ArrayRef< ExprType > v2)
Definition at line 34 of file IndexingUtils.cpp.
Referenced by mlir::computeElementwiseMul().
computeSuffixProductImpl()
template<typename ExprType > SmallVector<ExprType> computeSuffixProductImpl (ArrayRef< ExprType > sizes, ExprType unit)
Definition at line 23 of file IndexingUtils.cpp.
Referenced by mlir::computeSuffixProduct().
delinearizeImpl()
template<typename ExprType , typename DivOpTy > SmallVector<ExprType> delinearizeImpl (ExprType linearIndex, ArrayRef< ExprType > strides, DivOpTy divOp)
Definition at line 56 of file IndexingUtils.cpp.
Referenced by mlir::delinearize().
linearizeImpl()
template<typename ExprType > ExprType linearizeImpl (ArrayRef< ExprType > offsets, ArrayRef< ExprType > basis, ExprType zero)
Definition at line 46 of file IndexingUtils.cpp.
Referenced by mlir::linearize().